### ISSUE TITLE
Nil pointer derefrence

### ISSUE THREAD

**Issue by a86c6f7964** [prometheus/alertmanager#131] opened 2015-10-07 16:10 UTC
I have been having an alert going off for a while. It is just a warning. It also is flapping back and forth. I think that this is possibly causing this Nil pointer. I am not sure what is needed to make this issue more clear, so tell me if I can help.

I notice that there is a lot of logs about 'Recomputing notifications'
If I run `increase(prometheus_notifications_latency_milliseconds_count[10m])` I get 40. This to mean implies that prometheus is sending the alert every 15 seconds. There are 3 alerts going off. So this does not really make sense to me that I would see the 'Recomputing' every second.

I am running version 216d9dd:0.0.4 of prom/alertmanager from the docker registry, and I am running 64349aa:0.15.1 of prometheus.

```
Oct 07 15:58:51 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:58:51Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:58:52 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:58:52Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:58:53 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:58:53Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:58:54 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:58:54Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:58:55 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:58:55Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:58:56 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:58:56Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:58:57 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:58:57Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:58:58 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:58:58Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:58:59 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:58:59Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:59:00 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:59:00Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:59:01 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:59:01Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:59:02 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:59:02Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:59:03 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:59:03Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:59:04 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:59:04Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:59:05 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:59:05Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:59:06 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:59:06Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:59:07 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:59:07Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:59:08 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:59:08Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:59:09 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:59:09Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:59:10 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: time="2015-10-07T15:59:10Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: [signal 0xb code=0x1 addr=0x0 pc=0x4e532d]
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: goroutine 14 [running]:
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: github.com/prometheus/alertmanager/manager.(*memoryAlertManager).removeExpiredAggregates(0xc208125860)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/.build/gopath/src/github.com/prometheus/alertmanager/manager/manager.go:282 +0x23d
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: github.com/prometheus/alertmanager/manager.(*memoryAlertManager).runIteration(0xc208125860)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/.build/gopath/src/github.com/prometheus/alertmanager/manager/manager.go:395 +0x33
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: github.com/prometheus/alertmanager/manager.(*memoryAlertManager).Run(0xc208125860)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/.build/gopath/src/github.com/prometheus/alertmanager/manager/manager.go:408 +0x9a
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: created by main.main
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/main.go:111 +0xd50
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: goroutine 1 [chan receive, 24 minutes]:
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: github.com/prometheus/alertmanager/manager.(*notifier).Dispatch(0xc2080ae6c0)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/.build/gopath/src/github.com/prometheus/alertmanager/manager/notifier.go:816 +0x54
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: main.main()
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/main.go:157 +0x15c0
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: goroutine 19 [chan receive, 22 minutes]:
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: gopkg.in/fsnotify%2ev0.(*Watcher).purgeEvents(0xc208066240)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/.build/gopath/src/gopkg.in/fsnotify.v0/fsnotify.go:21 +0x55
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: created by gopkg.in/fsnotify%2ev0.NewWatcher
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/.build/gopath/src/gopkg.in/fsnotify.v0/fsnotify_linux.go:127 +0x43a
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: goroutine 18 [syscall, 24 minutes]:
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: syscall.Syscall(0x0, 0x3, 0xc208189ee0, 0x10000, 0x0, 0x0, 0x0)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: syscall.read(0x3, 0xc208189ee0, 0x10000, 0x10000, 0x0, 0x0, 0x0)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /usr/local/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: syscall.Read(0x3, 0xc208189ee0, 0x10000, 0x10000, 0x0, 0x0, 0x0)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /usr/local/go/src/syscall/syscall_unix.go:136 +0x58
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: gopkg.in/fsnotify%2ev0.(*Watcher).readEvents(0xc208066240)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/.build/gopath/src/gopkg.in/fsnotify.v0/fsnotify_linux.go:219 +0x12c
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: created by gopkg.in/fsnotify%2ev0.NewWatcher
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/.build/gopath/src/gopkg.in/fsnotify.v0/fsnotify_linux.go:126 +0x420
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: goroutine 13 [chan receive]:
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: main.func·001()
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/main.go:85 +0x84
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: created by main.main
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/main.go:90 +0x659
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: goroutine 15 [IO wait]:
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: net.(*pollDesc).Wait(0xc20809c840, 0x72, 0x0, 0x0)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: net.(*pollDesc).WaitRead(0xc20809c840, 0x0, 0x0)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: net.(*netFD).accept(0xc20809c7e0, 0x0, 0x7f6e0747ed70, 0xc2082c2b30)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /usr/local/go/src/net/fd_unix.go:419 +0x40b
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: net.(*TCPListener).AcceptTCP(0xc20804e438, 0x63a5ae, 0x0, 0x0)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: net/http.tcpKeepAliveListener.Accept(0xc20804e438, 0x0, 0x0, 0x0, 0x0)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /usr/local/go/src/net/http/server.go:1976 +0x4c
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: net/http.(*Server).Serve(0xc2080665a0, 0x7f6e07482658, 0xc20804e438, 0x0, 0x0)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /usr/local/go/src/net/http/server.go:1728 +0x92
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: net/http.(*Server).ListenAndServe(0xc2080665a0, 0x0, 0x0)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /usr/local/go/src/net/http/server.go:1718 +0x154
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: net/http.ListenAndServe(0x90ecf0, 0x5, 0x0, 0x0, 0x0, 0x0)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /usr/local/go/src/net/http/server.go:1808 +0xba
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: github.com/prometheus/alertmanager/web.WebService.ServeForever(0xc2080aef90, 0xc2080aefc0, 0xc20802fc20, 0xc208099360, 0x90ecf0, 0x5, 0x7ffff82c9e5a, 0x8, 0x0, 0x0)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/.build/gopath/src/github.com/prometheus/alertmanager/web/web.go:78 +0x8e6
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: created by main.main
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/main.go:145 +0x12f1
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: goroutine 16 [select, 24 minutes]:
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: github.com/prometheus/alertmanager/config.(*fileWatcher).Watch(0xc208033b40, 0xc2080aeff0)
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/.build/gopath/src/github.com/prometheus/alertmanager/config/watcher.go:49 +0x8fb
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: created by main.main
Oct 07 15:59:11 ip-172-31-23-215.us-west-2.compute.internal docker[18598]: /app/main.go:154 +0x14b0
```

everytime alertmanager panics, it restarts. It would be nice to know what is going on.

**Comment by juliusv** [comment] 2015-10-07 17:01
Hey @a86c6f7964, thanks for reporting this, and sorry this bit you!

This issue is a duplicate of https://github.com/prometheus/alertmanager/issues/122, so I'm closing this one.

This is unfortunately a known bug which happens when you have an alert which is *not* matched by any aggregation rule in the alertmanager, and when that alert then stops firing. As the current Alertmanager is marked as highly experimental, we are currently (finally) rewriting AM completely, so this issue will be obsoleted by the rewrite. It will probably not be fixed in the current experimental version before that though.

The recommendation for working around this crash bug is to always have a catch-all (no filters) aggregation rule at the end of your Alertmanager configuration file to ensure that no alerts go unmatched.

**Closed by juliusv** 2015-10-07 17:01 UTC
