### ISSUE TITLE
Webhook server fails when running HA example

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#835] opened 2017-05-30 14:22 UTC
I'm running this the HA example using `goreman start`, on arch linux.

I get this error output (the alertmanagers run fine):

```
16:16:39 wh | # command-line-arguments
16:16:39 wh | can't create $WORK/command-line-arguments.a: open $WORK/command-line-arguments.a: no such file or directory
16:16:39 wh | Terminating wh
```

A quick googling didn't reveal anything. Anyone seen this?

**Comment by mxinden** [comment] 2017-07-31 15:13
@stuartnelson3 I am not able to reproduce this on Arch Linux. Can you try to run `export WORK=/tmp` before?

**Comment by stuartnelson3** [comment] 2017-07-31 15:21
Happens when I export `$WORK` or when I declare it when invoking the `goreman` command. Full output:

```
# echo $WORK
/tmp
~/s/g/p/alertmanager (master %=)
# env TMPDIR=. WORK=/tmp goreman start
17:20:16 wh | Starting wh on port 5003
17:20:16 a2 | Starting a2 on port 5001
17:20:16 a3 | Starting a3 on port 5002
17:20:16 a1 | Starting a1 on port 5000
17:20:16 a1 | time="2017-07-31T17:20:16+02:00" level=info msg="Starting alertmanager (version=0.8.0, branch=master, revision=7de7cf38f9916a93e5a971b7852f2a6b449aa1b2)" source="main.go:109" 
17:20:16 a1 | time="2017-07-31T17:20:16+02:00" level=info msg="Build context (go=go1.8.1, user=stuartnelson@stuarch, date=20170731-15:17:29)" source="main.go:110" 
17:20:16 a1 | time="2017-07-31T17:20:16+02:00" level=info msg="Loading configuration file" file="examples/ha/alertmanager.yaml" source="main.go:237" 
17:20:16 a1 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:57107] connection accepted" component=mesh source="main.go:408" 
17:20:16 a3 | time="2017-07-31T17:20:16+02:00" level=info msg="Starting alertmanager (version=0.8.0, branch=master, revision=7de7cf38f9916a93e5a971b7852f2a6b449aa1b2)" source="main.go:109" 
17:20:16 a3 | time="2017-07-31T17:20:16+02:00" level=info msg="Build context (go=go1.8.1, user=stuartnelson@stuarch, date=20170731-15:17:29)" source="main.go:110" 
17:20:16 a3 | time="2017-07-31T17:20:16+02:00" level=info msg="Loading configuration file" file="examples/ha/alertmanager.yaml" source="main.go:237" 
17:20:16 a3 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:8001] attempting connection" component=mesh source="main.go:408" 
17:20:16 a2 | time="2017-07-31T17:20:16+02:00" level=info msg="Starting alertmanager (version=0.8.0, branch=master, revision=7de7cf38f9916a93e5a971b7852f2a6b449aa1b2)" source="main.go:109" 
17:20:16 a2 | time="2017-07-31T17:20:16+02:00" level=info msg="Build context (go=go1.8.1, user=stuartnelson@stuarch, date=20170731-15:17:29)" source="main.go:110" 
17:20:16 a2 | time="2017-07-31T17:20:16+02:00" level=info msg="Loading configuration file" file="examples/ha/alertmanager.yaml" source="main.go:237" 
17:20:16 a1 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:57107|00:00:00:00:00:03(c)]: connection ready; using protocol version 2" component=mesh source="main.go:408" 
17:20:16 a1 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:57107|00:00:00:00:00:03(c)]: connection added (new peer)" component=mesh source="main.go:408" 
17:20:16 a3 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:8001|00:00:00:00:00:01(a)]: connection ready; using protocol version 2" component=mesh source="main.go:408" 
17:20:16 a3 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:8001|00:00:00:00:00:01(a)]: connection added (new peer)" component=mesh source="main.go:408" 
17:20:16 a1 | time="2017-07-31T17:20:16+02:00" level=info msg="Listening on :9093" source="main.go:311" 
17:20:16 a2 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:8001] attempting connection" component=mesh source="main.go:408" 
17:20:16 a1 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:40691] connection accepted" component=mesh source="main.go:408" 
17:20:16 a2 | time="2017-07-31T17:20:16+02:00" level=info msg="Listening on :9094" source="main.go:311" 
17:20:16 a2 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:8001|00:00:00:00:00:01(a)]: connection ready; using protocol version 2" component=mesh source="main.go:408" 
17:20:16 a2 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:8001|00:00:00:00:00:01(a)]: connection added (new peer)" component=mesh source="main.go:408" 
17:20:16 a1 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:40691|00:00:00:00:00:02(b)]: connection ready; using protocol version 2" component=mesh source="main.go:408" 
17:20:16 a1 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:40691|00:00:00:00:00:02(b)]: connection added (new peer)" component=mesh source="main.go:408" 
17:20:16 a2 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:8002] attempting connection" component=mesh source="main.go:408" 
17:20:16 a2 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:49239] connection accepted" component=mesh source="main.go:408" 
17:20:16 a2 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:8002|00:00:00:00:00:02(b)]: connection shutting down due to error: cannot connect to ourself" component=mesh source="main.go:408" 
17:20:16 a2 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:49239|00:00:00:00:00:02(b)]: connection shutting down due to error: cannot connect to ourself" component=mesh source="main.go:408" 
17:20:16 a3 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:8003] attempting connection" component=mesh source="main.go:408" 
17:20:16 a3 | time="2017-07-31T17:20:16+02:00" level=info msg="Listening on :9095" source="main.go:311" 
17:20:16 a3 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:50035] connection accepted" component=mesh source="main.go:408" 
17:20:16 a3 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:50035|00:00:00:00:00:03(c)]: connection shutting down due to error: cannot connect to ourself" component=mesh source="main.go:408" 
17:20:16 a3 | time="2017-07-31T17:20:16+02:00" level=debug msg="->[127.0.0.1:8003|00:00:00:00:00:03(c)]: connection shutting down due to error: cannot connect to ourself" component=mesh source="main.go:408" 
17:20:16 wh | # command-line-arguments
17:20:16 wh | can't create $WORK/command-line-arguments.a: open $WORK/command-line-arguments.a: no such file or directory
17:20:16 wh | Terminating wh
```

**Comment by simonpasquier** [comment] 2018-03-16 10:09
@stuartnelson3 I had the same error as you but upgrading `goreman` made it go away.

**Comment by simonpasquier** [comment] 2019-09-19 07:38
Closing this since it looks fixed.

**Closed by simonpasquier** 2019-09-19 07:38 UTC
Labels: area/developer tooling, component/high availability, kind/bug, priority/Pmaybe
