### ISSUE TITLE
Alertrules Cronjob

### ISSUE THREAD

**Issue by lissa091** [prometheus/alertmanager#896] opened 2017-07-06 15:03 UTC
I want to create an alert rule for monitoring a cronjob. I want to see if the cronjob execution time is not older than 5 minutes. So i got a metric with the timestamp of the cronjob. 
My idea is to compare the timestamp in the metric with "date --date="5 minutes ago" +%s " but how can i realize this in the .rules file? 

ALERT cron_example
  IF cron_example < date --date="5 minutes ago" +%s 
LABELS { severity = "critical" }
  ANNOTATIONS {
    summary = "Instance {{$labels.instance}}: Fileserver {{$labels.title}}",
    description = "Instance {{$labels.instance}}: Fileserver {{$labels.title}} with Error a count of {{ $value }}"
  }

This failed and prometheus do not start anymore when this alert is activated.

**Comment by devinodaniel** [comment] 2017-07-06 17:15
Hey @lissa091, using the [promtool](github.com/prometheus/prometheus/cmd/promtool) I ran `check-rules` on your rule and it returned ```FAILED: parse error at line 2, char 31: no valid statement detected```. It looks like your query may be invalid.

**Comment by juliusv** [comment] 2017-07-06 18:00
Yeah, that's not a valid PromQL query and not a bug in Alertmanager. Closing.

See https://prometheus.io/docs/practices/alerting/#batch-jobs for general batch job alerting and also see https://www.digitalocean.com/community/tutorials/how-to-query-prometheus-on-ubuntu-14-04-part-2#step-4-—-working-with-timestamp-metrics for how to work with timestamp metrics.

**Closed by juliusv** 2017-07-06 18:00 UTC
