### ISSUE TITLE
API shows briefly reports alerts as not being silenced until silences are applied

### ISSUE THREAD

**Issue by mattbostock** [prometheus/alertmanager#609] opened 2017-01-18 12:14 UTC
We're using the `/v1/alerts/groups` API endpoint to query all alerts and show them on dashboard using an internal tool.

This works well, except when Alertmanager is restarted for a deployment. The `silenced` field exposed by the above endpoint is populated by the dispatcher, which has to iterate through every alert and set the silenced field when AlertManager starts up. If you have thousands of alerts, this can take a while, and in the meantime our dashboard shows lots of alerts we know are silenced.

This bug report is not very detailed yet and happy to provide more info, but I'm raising it early in case there are some plans afoot to change this behaviour.

**Comment by prymitive** [comment] 2017-02-10 03:08
This seems to be only affecting API, notifications always obey silences. API seems to expose internal state without any indication if the silence matching was done for an alert or not, while notification path is likely to wait until silences are checked.
And this doesn't only happen during restart, if there is a flood of alerts that should be silenced some will initially show as silenced and some will lack silence matched in the API, this resolved after a few minutes, so it does look like AM is simply lagging with matching alerts and silences when there is a batch of new alerts.

**Comment by lukasz-cf** [comment] 2017-03-27 21:17
Would it be acceptable to solve this by:

- add a new field `processed` to alerts (probably needs a better name), defaulting to false
- set `processed = true` in https://github.com/prometheus/alertmanager/blob/503a6c0569b1225d41347c6ff1570c6b12f93b39/types/types.go#L78
- in the API only return alerts with `processed == true` (not sure where should this live)

?

**Comment by prymitive** [comment] 2017-03-27 21:19
Would it be acceptable to solve this by:

* add a new field processed to alerts (probably needs a better name), defaulting to false
* set processed = true in https://github.com/prometheus/alertmanager/blob/503a6c0569b1225d41347c6ff1570c6b12f93b39/types/types.go#L78
* in the API only return alerts with processed == true (not sure where should this live)

?

**Comment by mattbostock** [comment] 2017-03-28 08:48
:+1: That's roughly the approach I was thinking of. We should cater for inhibited alerts also.

It might make sense to add separate fields for marking silences and inhibition rules as being 'processed' to the `Alert` type:
https://github.com/prometheus/alertmanager/blob/503a6c0569b1225d41347c6ff1570c6b12f93b39/types/types.go#L132-L144

**Comment by prymitive** [comment] 2017-03-31 00:11
I'm trying to come up with a PR for this, I looked over the code and seems I need something like [this](https://github.com/prymitive/alertmanager/commit/84595967df380a1f0f77b4b1db2ea418cb1ec603), but I'm still reading into the codebase

**Comment by lukasz-cf** [comment] 2017-04-03 23:38
I tried to test those changes locally and it does seem to be doing the right thing, but it breaks tests at random, as some time constrains are now violated. I need to spend some time looking into that and implement test fixes & and add tests covering this feature. But would be nice if I got a confirmation that the direction of this change is correct.

**Comment by prymitive** [comment] 2017-04-03 23:38
I tried to test those changes locally and it does seem to be doing the right thing, but it breaks tests at random, as some time constrains are now violated. I need to spend some time looking into that and implement test fixes & and add tests covering this feature. But would be nice if I got a confirmation that the direction of this change is correct.

**Comment by prymitive** [comment] 2017-04-04 16:43
I did investigate those test errors and couldn't find how they are related to my change, after re-running those on master I see that it also fails there https://gist.github.com/prymitive/017a6bd77fe1768cca78a28e352c8191
that's on 0.5.1:

```
$ git log --oneline -n 1
0ea1cac *: cut v0.5.1 (#569)
```

So it doesn't look that my change is causing any regression. I will work on adding tests cases to the code, I did some scripted testing yesterday that seemed to work as expected.

**Comment by prymitive** [comment] 2017-04-04 17:05
FYI here's a log of my testing - https://gist.github.com/prymitive/4d2ae3f9bdab981fc40e4153654d506e
I've started AM instance using sample config (with empty data dir) and run alerts.py & checks.py in two console tabs, alerts.py was creating new alerts while checks.py was querying AM API for alerts
One test run on latest master branch and the second one was with alertmanager binary compiled from a branch with this small patch - https://github.com/prymitive/alertmanager/commit/84595967df380a1f0f77b4b1db2ea418cb1ec603

**Comment by prymitive** [comment] 2017-04-14 18:52
The discussion from #692 leads us to some more changes:

- drop `inhibited` and `silenced` from marker and replace it with `status` field, which will default to `unprocessed`
- refactor `SetSilenced` and `SetInhibited` to update `status` instead of dedicated fields
- always return all alerts, but now with additional `status` field that the client can use to tell if alert was processed or not (solves this issue)

Unsure about:
- have silence id in the alert response, it was mentioned we could just have `status: silenced`, but some clients (like [unsee](https://github.com/cloudflare/unsee)) use this information to display silence details, I'll try to address this here as well.

**Comment by prymitive** [comment] 2017-04-29 04:45
Since #717 was merged I think we can close this, thanks

**Comment by mxinden** [comment] 2017-08-13 13:53
As suggested by @prymitive I will close here.

**Closed by mxinden** 2017-08-13 13:53 UTC
