### ISSUE TITLE
Add notification sent count and duration metrics with tag receiver name

### ISSUE THREAD

**Issue by zhaojinxin409** [prometheus/alertmanager#2793] opened 2021-12-20 06:38 UTC
**What did you expect to see?**

Add notification sent count and duration metrics with tag `receiver name`, i think it will be useful to know the receiver status.

* Example:

Alertmanager config:

```
receivers:
- name: notify-a
  webhook_configs:
  - url: http://url-a
- name: notify-b
  webhook_configs:
  - url: http://url-b
```

Metrics:

```
alertmanager_notification_sent_total{recevier="notify-a"} 2
alertmanager_notification_sent_failed_total{recevier="notify-a"} 1
alertmanager_notification_sent_duration{recevier="notify-a", le=0.1} 1
```

**Comment by simonpasquier** [comment] 2022-01-26 15:29
Closing as a duplicate of https://github.com/prometheus/alertmanager/issues/2527

**Closed by simonpasquier** 2022-01-26 15:29 UTC
