### ISSUE TITLE
What's the correct way to config Alertmanager to use a forward proxy?

### ISSUE THREAD

**Issue by eugene-chow** [prometheus/alertmanager#853] opened 2017-06-08 15:09 UTC
In this [thread](https://github.com/coreos/prometheus-operator/issues/399#issuecomment-307114123) with @brancz, I was seeking a way to config Alertmanager to use a forward proxy. One way is to use the `https_proxy` env var detailed [here](https://github.com/prometheus/alertmanager/issues/628).

Is this the correct way to do it in the long haul, or should it be in Alertmanager's config. Thanks!

**Comment by brancz** [comment] 2017-06-08 17:42
As mentioned in the other thread, all Prometheus projects are exclusively configured via config files, and that this is configurable via an environment variable right now is purely a coincidence because of the underlying http client implementation.

I'd propose that an `http_proxy` config maybe to be consistent with Prometheus we should also call it `proxy_url` (see https://prometheus.io/docs/operating/configuration/#scrape_config). That configuration should then be available/implemented for all existing notification providers.

**Comment by brian-brazil** [comment] 2017-06-08 17:50
For blackbox I'm getting the common http bits broken out to a library in common, which we could also use here.

**Comment by brancz** [comment] 2017-06-12 08:42
@brian-brazil is this already in process?

**Comment by brian-brazil** [comment] 2017-06-12 08:47
https://github.com/prometheus/common/pull/81 I must look at it again

**Comment by brian-brazil** [comment] 2017-06-21 12:10
That's submitted over in common, so should be good to go here.

**Comment by brancz** [comment] 2017-07-21 13:26
With the changes merged from prometheus/common#81, this can now be implemented here.

@brian-brazil what are your thoughts on where/how to integrate the HTTP config into the alertmanager config? An optional global and then an optional on every receiver config interacting with HTTP?

**Comment by brian-brazil** [comment] 2017-07-21 15:08
That's fine in principle, the problem is how we'd deal with the case where there's both a global and a per-receiver config. How should they be merged and/or overridden? Probably overridden.

**Comment by brancz** [comment] 2017-07-21 15:21
Yes I think if specified in a receiver then it overrites the global, no merging would be my suggestion as well.

**Comment by brian-brazil** [comment] 2017-07-21 15:24
That just leaves how to implement that then. Maybe do this as a named "http_config" rather than the usual inlining?

**Comment by brancz** [comment] 2017-07-21 16:50
Yes that was my idea as well.

**Comment by brian-brazil** [comment] 2018-03-29 10:38
This was done.

**Closed by brian-brazil** 2018-03-29 10:38 UTC
Labels: component/notify, kind/enhancement

**Comment by azizzoaib786** [comment] 2018-07-25 13:54
Based on documentation .. inside alertmanager.yml file, we can define as below:

global:
hipchat_api_url: 'https://company.hipchat.com'
http_config:
proxy_url: 'http://(IP):3128'

**Comment by brettjacobson** [comment] 2019-01-25 12:51
In case someone else lands here;
https://prometheus.io/docs/alerting/configuration/#http_config

Also, the underlying library DOES seem to automatically support NTLM authentication in `basic_auth` mode, but it is undocumented.
