### ISSUE TITLE
Alertmanager sends the resolved messages continuously

### ISSUE THREAD

**Issue by tsboj17** [prometheus/alertmanager#611] opened 2017-01-24 14:13 UTC
This problem is totally same as this closed issue: https://github.com/prometheus/alertmanager/issues/246

I changed the `resolve_timeout` parameter as you suggested but it did not help.

**Comment by bkupidura** [comment] 2017-01-24 14:23
Hello, please check my comment from https://github.com/prometheus/alertmanager/issues/246#issuecomment-272196116

Moreover i observed that overwritting prometheus_pod and prometheus_ip helps a little (I got multiple resolved notification, but less than previous) :)

```
alerting:
  alert_relabel_configs:
    - source_labels: [prometheus_pod]
      action: replace
      replacement: prometheus
      target_label: prometheus_pod
    - source_labels: [prometheus_ip]
      action: replace
      replacement: prometheus
      target_label: prometheus_ip
```

**Comment by onlinegangster** [comment] 2017-02-16 12:34
I have the same problem, however it seems that the problem is coming from prometheus itself which keeps sending the notifications, this is what I see when I enable debug logging in the alertmanager: 
```
DEBU[0778] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0778] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0778] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0788] Received alert                                alert=service_down[878a779][resolved] component=dispatcher source=dispatch.go:168
DEBU[0788] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0788] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0788] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0803] Received alert                                alert=service_down[878a779][resolved] component=dispatcher source=dispatch.go:168
DEBU[0808] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0808] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0808] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0818] Received alert                                alert=service_down[878a779][resolved] component=dispatcher source=dispatch.go:168
DEBU[0818] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0818] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0818] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0833] Received alert                                alert=service_down[878a779][resolved] component=dispatcher source=dispatch.go:168
DEBU[0838] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0838] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0838] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0848] Received alert                                alert=service_down[878a779][resolved] component=dispatcher source=dispatch.go:168
DEBU[0848] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0848] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
DEBU[0848] flushing [service_down[878a779][resolved]]    aggrGroup=a4512f4ad56ffb9c source=dispatch.go:405
```

**Comment by brian-brazil** [comment] 2017-02-16 16:13
Prometheus sends alerts every eval interval, this is by design.

**Comment by onlinegangster** [comment] 2017-02-17 09:11
Actually these are not alerts but "resolved notifications"

**Comment by radut** [comment] 2017-03-17 22:43
so how can we actually filter resolved notifications, after being sent once ?

**Comment by radut** [comment] 2017-03-17 23:07
I have tested docker tag v0.4.2 and it works as expected, but v0.5.0 and v0.5.1 does send continuously the resolved information

**Comment by mattbostock** [comment] 2017-04-10 15:30
We're also seeing this issue in 0.5.1 (0.4.2 worked as expected).

**Comment by fabxc** [comment] 2017-04-10 15:33
Hard to debug without the exact alert and notification sequences, but this is most likely a known regression other issued were filed about already. @brancz is working on it right now.

**Comment by mattbostock** [comment] 2017-04-10 15:50
Looks like this may be https://github.com/prometheus/alertmanager/issues/598.

**Comment by brancz** [comment] 2017-04-10 16:31
I'll soon have a fix to test out.

**Closed** 2017-04-17 12:19 UTC
