### ISSUE TITLE
discord support?

### ISSUE THREAD

**Issue by Menogus** [prometheus/alertmanager#2455] opened 2021-01-15 14:52 UTC
is any support for discord now?

**Comment by SuperQ** [comment] 2021-01-21 16:50
This is a duplicate of https://github.com/prometheus/alertmanager/issues/1365

**Comment by SuperQ** [comment] 2021-01-21 16:51
https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver

**Closed by SuperQ** 2021-01-21 16:51 UTC
Labels: reviewed/duplicate
