### ISSUE TITLE
[Kubernetes] Peers ip caching causes all clusters to degrade over  time

### ISSUE THREAD

**Issue by grzesuav** [prometheus/alertmanager#2250] opened 2020-05-05 12:14 UTC
**What did you do?**

We have deployed several different `Alertmanager`'s - in different namespaces

**What did you expect to see?**

Each alertmanager installation forms a separate cluster

**What did you see instead? Under which circumstances?**

After some time, we noticed that all those installation form one big cluster.
We think that :
* address of peer passed via `--cluster.peer=DNS address` is resolved to IP address and later on, this ip address is used
* alertmanager instance is restarted/evicted to different node/etc and ip address can be assigned to other pod, which accidently happens to be ip address of alertmanager instance from other cluster
* they join in a one big cluster 

**Environment**

Kubernetes cluster

* System information:

	will add if needed

* Alertmanager version:

	insert output of `alertmanager --version` here

Different versions - 020, 0.17, 0.18

* Prometheus version:

	not related
  

* Alertmanager configuration file:

will add if needed

* Prometheus configuration file:

will add if needed

* Logs:

will add if needed

**Comment by simonpasquier** [comment] 2020-05-06 09:49
Can you elaborate about your setup? Which names do you use for `--cluster.peer`?
Alertmanager will try to reconnect to a previously known IP address for 6 hours by default. After this, it will forget about it.

**Comment by grzesuav** [comment] 2020-05-07 08:52
hi @simonpasquier ,
so my alertmanager pod arg line looks like 
```
  - args:
    - --config.file=/etc/alertmanager/config/alertmanager.yaml
    - --cluster.listen-address=[$(POD_IP)]:9094
    - --storage.path=/alertmanager
    - --data.retention=120h
    - --web.listen-address=:9093
    - --web.external-url=https://alertmanager-address
    - --web.route-prefix=/
    - --cluster.peer=alertmanager-main-0.alertmanager-operated.namespace.svc:9094
    - --cluster.peer=alertmanager-main-1.alertmanager-operated.namespace.svc:9094
    - --cluster.peer=alertmanager-main-2.alertmanager-operated.namespace.svc:9094
```

and yes, fresh after hard reset of all instances in the same time it starts with three peers. But previously it has cluster formed along  with all other alertmanager installations in our cluster (over 50 instances I guess ?)


So, from what you are saying, if during those 6 hours, ip gets re-assigned to completely different pod, AM will try to form cluster with this new pod ?

**Comment by simonpasquier** [comment] 2020-05-13 12:55
> So, from what you are saying, if during those 6 hours, ip gets re-assigned to completely different pod, AM will try to form cluster with this new pod ?

yes

**Comment by simonpasquier** [comment] 2020-05-13 12:56
BTW you can set the `--cluster.reconnect-timeout` flag to a lower value than the default 6 hours.

**Comment by grzesuav** [comment] 2020-05-19 20:14
Actually I try to resolve it with NetworkPolicies, however it is still workaround. I would still consider this as something which should be handled or at least mention in documentation (we are using prometheus operator so relay a bit on defaults there) as in our case silencing alert on one alertmanager caused somebody else missed notification.

**Comment by bjakubski** [comment] 2020-06-15 16:20
I've found this issue when trying to figure out why alertmanagers formed a mesh over cluster boundaries. I was investigating because of alerts about alertmanager being in inconsistent state fired, and nothing more serious happened.
Same story - prometheus-operator, k8s.
Granted, the issue was caused mostly by a misconfiguration on our side (different cluster has same ip range and is routable).

I do find it surprising that alertmanager (often used in dynamic envs like k8s) will not try to resolve the names on every connection attempt

**Comment by hwoarang** [comment] 2020-08-03 14:11
> BTW you can set the `--cluster.reconnect-timeout` flag to a lower value than the default 6 hours.

That's a reasonable suggestion but prometheus operator does not let you pass additional parameters to the alertmanager instance. But all in all, this is something that needs to be addressed there of course.

**Comment by b10s** [comment] 2021-09-06 07:29
I've got the same issue and able to reproduce. How to reproduce is in second comment in the following issue:
https://github.com/hashicorp/memberlist/issues/241#issuecomment-912343436

I think it is nature of gossip protocol which should be suppressed a bit by alertmanager since it has knowledge of peers from config file and can verify the table of available peers.

**Comment by b10s** [comment] 2021-11-05 14:18
There is also one possible solution is to add cluster id:
https://groups.google.com/g/prometheus-developers/c/wJ60O2Mk3js/m/qixf31fRBQAJ

**Comment by simonpasquier** [comment] 2023-09-26 09:37
this should be fixed by https://github.com/prometheus/alertmanager/pull/3354 which allows to define a label identifying the cluster and preventing external instances to join the cluster if they don't share the same label.

**Closed by simonpasquier** 2023-09-26 09:37 UTC
Labels: component/high availability
