### ISSUE TITLE
Requesting AWS SNS topic support be added natively to AlertManager

### ISSUE THREAD

**Issue by kevinayres** [prometheus/alertmanager#2583] opened 2021-05-15 23:26 UTC
AWS SNS is a common text/sms alerting mechanism I'm seeing requested more and more.  There is a fairly clunky project called alertmanager-sns-forwarder which has not been worked on in a long time. It would be advantageous to have SNS supported natively in alertmanager.

**Comment by roidelapluie** [comment] 2021-05-16 05:59
Duplicate of #2559

**Closed by roidelapluie** 2021-05-16 05:59 UTC
