### ISSUE TITLE
it's more useful for webhook_config support template and custom the header

### ISSUE THREAD

**Issue by fzhsh-q** [prometheus/alertmanager#2268] opened 2020-05-26 03:05 UTC
why not `webhook_config` support the template and custom the header? most of the time, we just modify configuration file to integrations custom alert system

**Comment by simonpasquier** [comment] 2020-05-26 14:05
Duplicate of #701 and https://github.com/prometheus/alertmanager/pull/2184. So far we haven't reached a consensus on it.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Closed by simonpasquier** 2020-05-26 14:05 UTC

**Comment by fzhsh-q** [comment] 2020-05-27 01:35
tks
