### ISSUE TITLE
I hope when alert in silence status, I can receive the notice that alert has been resolved 

### ISSUE THREAD

**Issue by hw4liu** [prometheus/alertmanager#2805] opened 2021-12-29 07:36 UTC
**What did you expect to see?**

I hope when an alert is in silence status, I can receive the notice that the alert has been resolved .

when I use alertmanager, I am sure the message be sent to alertmanager must has endsAt time， 

Let me describe how we used,
1. when an alert has been sent to the user
2. user ack this alert, make the alert be silenced 15 minutes
3. but just 5 minutes this alert has been resolved, and now this alert during be silenced time, I want to receive resolved message 

* Alertmanager version:

```
  alertmanager, version 0.22.2 (branch: HEAD, revision: 44f8adc06af5101ad64bd8b9c8b18273f2922051)
  build date:       20210602-07:50:37
  go version:       go1.16.4
  platform:         linux/amd64
```

* Alertmanager configuration file:
```
global:
  resolve_timeout: 30d

route:
  group_by: ['app', 'id', 'rule', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  receiver: 'webhook'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['id']

receivers:
- name: 'webhook'
  webhook_configs:
    - url: 'http://127.0.0.1:8888/xxxxx'
```

**Comment by jeyrce** [comment] 2021-12-31 08:57
It provided a api to notify a server when silence expired in some old version but removed now. So that seems we can only search the result by self.

**Comment by hw4liu** [comment] 2022-01-05 05:57
https://github.com/prometheus/alertmanager/pull/2811 
I have a pull request, it can make message can be sent when alert in silence

**Comment by simonpasquier** [comment] 2022-01-20 10:08
this is a duplicate of #226

**Comment by hw4liu** [comment] 2022-01-26 03:27
It looks like yes, I've used it in production and can achieve the purpose of receiving resolved messages during silent periods. In my implementation, a configuration file parameter "receive_silence_resolved" has been added to ensure that the resolved message is obtained during the execution phase of 'MuteStage' and sent out through the webhook. Now should I update the document?

**Comment by simonpasquier** [comment] 2022-03-04 14:26
I'm going to close this in favor of #226 since @sthaha should start collecting requirements soon.

**Closed by simonpasquier** 2022-03-04 14:26 UTC
