### ISSUE TITLE
Nightly silence, and Weekends.

### ISSUE THREAD

**Issue by raypettersen** [prometheus/alertmanager#517] opened 2016-09-28 13:18 UTC
I'm having trouble finding the doc for creating a nightly silence, or silence days like for example weekends. Any pointers would be greatly appreciated.

**Comment by raypettersen** [comment] 2016-09-29 18:41
I take it there isn't a clear way of doing this through the web interface? Is the API a workaround by the use of scripting?

**Comment by juliusv** [comment] 2016-09-29 18:46
Yeah, AM doesn't support regularly scheduled silences at certain times. You'd have to use the API to create your own regular silences. The API isn't documented or guaranteed to be stable yet, but can be used already. Just look in your browser's inspector to see what the AJAX requests look like when creating a silence...

**Comment by raypettersen** [comment] 2016-09-29 18:47
Cheers. Perhaps this should be marked as a feature request if it isn't already a duplicate?

**Comment by juliusv** [comment] 2016-09-29 18:47
Yeah, @fabxc could maybe comment on whether he'd ever want to have that as a feature in AM or considers it out of scope.

**Comment by raypettersen** [comment] 2016-10-01 11:07
@fabxc this feature is really important to us as we are moving away from zabbix. and have a couple of nightly jobs that is currently triggering alert in our prometheus-alertmanager setup. Any hope of seeing it implemented in alertmanager in the future?

**Comment by matthiasr** [comment] 2016-10-01 15:21
Another way would be to make the alert not fire at all while the job is running. Obviously this needs some way to determine by query whether that is so. The new time functions might help, but a direct indication may be less fragile.

Then you can incorporate that in your queries directly, or have a separate "alert" this fact, route it nowhere, and let it inhibit the noisy ones.

**Comment by raypettersen** [comment] 2016-10-01 15:42
I've been playing around with the api, and had some success.

`curl --data '{"matchers":[{"name":"alertname","value":"ASAHighConnections","isRegex":false},{"name":"alias","value":"asa.host.domain","isRegex":false}],"startsAt":"2016-10-01T15:33:00.000Z","endsAt":"2016-10-01T19:33:00.000Z","createdBy":"email@email.com","comment":"testing"}' http://localhost:9093/api/v1/silences
`
-OK-

This should be enough for creating a workaround for the time being, while I wait for a more functional webgui approach. Looking forward to seeing this project evolve. Could this issue be re-branded to feature request?

**Comment by LarsAlmgren** [comment] 2017-09-11 14:28
+1

**Comment by adamdifelice** [comment] 2018-01-26 14:26
:+1:

**Comment by brian-brazil** [comment] 2018-01-26 14:35
I'm confused as to what the feature request is supposed to be here. Maybe you're looking for #876?

**Comment by adamdifelice** [comment] 2018-01-26 14:41
I followed both, but yes that is the same feature

**Comment by brian-brazil** [comment] 2018-01-26 14:43
This is a duplicate of #876 then.

**Closed by brian-brazil** 2018-01-26 14:43 UTC
Labels: area/usability, kind/enhancement
