### ISSUE TITLE
Silence editor: must use ISO 8601 date format

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#189] opened 2015-12-10 14:31 UTC
Local date formats are PITA in any globalized work context. As we are using UTC everywhere as time zone, we also must use ISO 8601 date format everywhere.

Not sure if that works with the browser's built-in date picker of if we need a custom one.

http://xkcd.com/1179/
https://en.wikipedia.org/wiki/ISO_8601

**Comment by brian-brazil** [comment] 2015-12-17 11:25
Dupe of #94

**Closed by brian-brazil** 2015-12-17 11:25 UTC
