### ISSUE TITLE
regex checkbox not clickable in firefox

### ISSUE THREAD

**Issue by joker234** [prometheus/alertmanager#490] opened 2016-09-05 16:07 UTC
When I want to create a silence in the Alertmanager with Firefox, I can't use the regex checkbox. Also checked with chromium. There it's working.

Chromium:
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116
```
Firefox:
```
Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
```
Alertmanager:
```
branch 	 	master
buildDate 	20160905-16:00:39
goVersion 	go1.7
revision 	d263b7ab9aa8ae6213b45ba3c959d02c9600955c
version 	0.3.0
```

P.S.: this is no new issue for me. I just checked it again with current master of alertmanager and had time to report it.

**Comment by juliusv** [comment] 2016-09-05 21:30
Thanks!

This is a dupe of https://github.com/prometheus/alertmanager/issues/436, which is fixed and will be released with 0.4.2.

Closing.

**Comment by juliusv** [comment] 2016-09-05 21:31
@joker234 Hm wait, you said you still have the problem with current master? Could you re-confirm? Reopening for now.

**Comment by juliusv** [comment] 2016-09-05 21:34
Ah, that's currently not in the master branch, but in release-0.4 branch: https://github.com/prometheus/alertmanager/commits/release-0.4

So that's why you still see it in master. Will be fixed in the next release though. Closing again.

**Closed by juliusv** 2016-09-05 21:34 UTC

**Comment by joker234** [comment] 2016-09-06 12:30
thanks for the answers. So what is recommended to use in general? master or any other branch?

**Comment by fabxc** [comment] 2016-09-06 12:53
@grobie backporting all the UI fixes right now will delay the HA AM alpha a lot further. Especially with all the changes of pagniation and using bootstrap now.
 It worked far-from-good-but-okay for many users previously for months.

I tried backporting the basic fixes, but am relatively confused. The checkbox fix in question is here: https://github.com/prometheus/alertmanager/commit/9729d2db1651f9aae6fdb72075946145c2ec38c1

However, that's a regression from the changes in `release-0.4` though as `master` is doing this correctly in the old version: https://github.com/prometheus/alertmanager/blob/master/ui/app/partials/silence-form.html#L27

So is something else for the same checkbox broken in master? Was this accidentally fixed by previous changes in `release-0.4`?

**Comment by grobie** [comment] 2016-09-06 14:48
Almost all the UI changes were real bugs. I'm against a new alertmanager release which includes a couple of regressions but not backporting whatever is necessary to master. I'm also against a release strategy where completely different feature sets get provided, that's confusing.

Let's have a hangout with @stuartnelson3, go through the differences and discuss what needs to be ported and who'll work on that.

**Comment by fabxc** [comment] 2016-09-06 15:10
FWIW, I believe people would rather not delay an HA AM by another 2 weeks or so due to some UI bugs we let them live with for months up until recently. Remember, this would merely be the first (of probably several alpha releases) – we would of course address this before the first RC.

Anyway, if we can get it done within this week, it's fine by me. But let's not go through another meeting just to coordinate fixes and back ports. I'm happy to to provide the necessary backend functionality as necessary.

@stuartnelson3

**Comment by fabxc** [comment] 2016-09-06 15:59
Realistically, if I implement the backend changes there's probably 0 change required in the frontend. I'm on it.

**Comment by grobie** [comment] 2016-09-06 16:06
Cool. I'm fine with broken behavior in alpha/rc releases. I'd prefer not re-introducing bugs in the next stable release.

**Comment by stuartnelson3** [comment] 2016-09-06 17:03
Let me know if I can help, and what level of attention we want to give the front end if it might be potentially changing drastically soon.
