### ISSUE TITLE
AlertManager - .GeneratorURL doesn't expand correctly more complex (only?) alert's conditions

### ISSUE THREAD

**Issue by it-praktyk** [prometheus/alertmanager#905] opened 2017-07-14 07:21 UTC
I've found that .GeneratorURL doesn't expand correctly more complex (only?) alert's conditions

A part of template - the file https://github.com/prometheus/alertmanager/blob/master/template/default.tmpl#L130-L138

```html
<tr>
    <td class="content-block">
    <strong>Labels</strong><br />
    {{ range .Labels.SortedPairs }}{{ .Name }} = {{ .Value }}<br />{{ end }}
    {{ if gt (len .Annotations) 0 }}<strong>Annotations</strong><br />{{ end }}
    {{ range .Annotations.SortedPairs }}{{ .Name }} = {{ .Value }}<br />{{ end }}
    <a href="{{ .GeneratorURL }}">Source</a><br />
    </td>
</tr>
```

for the alert definition

```
ALERT storage_90_percent
IF round((node_filesystem_free{job="nodes",mountpoint!="/var/lib/nfs/rpc_pipefs"} / node_filesystem_size{job="nodes"}) * 100, 1) <= 10 and on (device) node_filesystem_readonly != 1
FOR 10m
LABELS { severity = "critical", category = "storage"  }
ANNOTATIONS {
  summary= 'Free space on a storage is less than 10%',
  description= 'Free space on a storage is less 10%'
}
```

is expanded for

```html
<tr style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">
    <td style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; vertical-align: top; margin: 0; padding: 0 0 20px;" valign="top">
    <strong style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">Labels</strong><br style="font-family: 'Helvetica Neue', H
elvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
    alertname = storage_90_percent<br style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />category = storage<br style="f
ont-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />device = euhpc-nas02.euhpc.arm.com:/ifs/arm/ref<br style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />fstype = nfs<br style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />instance = bc-d6-2-8.eu.iaas.arm.com:9100<br style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />job = nodes<br style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />monitor = prometheus-server<br style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />mountpoint = /arm/ref<br style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />severity = critical<br style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
    <strong style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;">Annotations</strong><br style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
    description = Free space on a storage is less 10%<br style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />summary = Free space on a storage is less than 10%<br style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
    <a href="http://HOST_NAME:PORT_NUMBER/graph?g0.expr=round%28%28node_filesystem_free%7Bjob%3D%22nodes%22%2Cmountpoint%21%3D%22%2Fvar%2Flib%2Fnfs%2Frpc_pipefs%22%7D&#43;%2F&#43;node_filesystem_size%7Bjob%3D%22nodes%22%7D%29&#43;%2A&#43;100%2C&#43;1%29&#43;%3C%3D&#43;10&#43;and&#43;ON%28device%29&#43;node_filesystem_readonly&#43;%21%3D&#43;1&amp;g0.tab=0" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; color: #348eda; text-decoration: underline; margin: 0;">Source</a><br style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />
    </td>
</tr>
```

It was previously [posted](https://groups.google.com/forum/#!topic/prometheus-developers/wc03_aukKTc) at Prometheus Developers Google Group.

**Comment by brian-brazil** [comment] 2017-07-14 07:24
What exactly do you believe is a bug here?

**Comment by it-praktyk** [comment] 2017-07-14 07:31
The part href of <a> tag
```
href="http://HOST_NAME:PORT_NUMBER/graph?g0.expr=round%28%28node_filesystem_free%7Bjob%3D%22nodes%22%2Cmountpoint%21%3D%22%2Fvar%2Flib%2Fnfs%2Frpc_pipefs%22%7D&#43;%2F&#43;node_filesystem_size%7Bjob%3D%22nodes%22%7D%29&#43;%2A&#43;100%2C&#43;1%29&#43;%3C%3D&#43;10&#43;and&#43;ON%28device%29&#43;node_filesystem_readonly&#43;%21%3D&#43;1&amp;g0.tab=0
```
![selection_008](https://user-images.githubusercontent.com/4910261/28202740-a0943b20-686e-11e7-9a2a-c09eff110e9e.png)

**Comment by cornelf** [comment] 2017-07-14 16:07
what about allowing https protocol in the externalURL build
also port should be an option

it looks like a full external-url override is preferable to building it from bits and mixing logic in.

**Comment by mxinden** [comment] 2017-07-27 15:22
@it-praktyk Can you elaborate further on your bug description?

When I decode:
```
http://HOST_NAME:PORT_NUMBER/graph?g0.expr=round%28%28node_filesystem_free%7Bjob%3D%22nodes%22%2Cmountpoint%21%3D%22%2Fvar%2Flib%2Fnfs%2Frpc_pipefs%22%7D&#43;%2F&#43;node_filesystem_size%7Bjob%3D%22nodes%22%7D%29&#43;%2A&#43;100%2C&#43;1%29&#43;%3C%3D&#43;10&#43;and&#43;ON%28device%29&#43;node_filesystem_readonly&#43;%21%3D&#43;1&amp;g0.tab=0
```

I get the following query:
```
round(
  (
    node_filesystem_free{
      job="nodes",mountpoint!="/var/lib/nfs/rpc_pipefs"
    }
    +/+
    node_filesystem_size{
      job="nodes"
    }
  )+*+100,+1
)+
<=+
10+

and

+ON(
  device
)+node_filesystem_readonly+!=+1

```

**Comment by it-praktyk** [comment] 2017-07-31 11:44
I expect that encoded URLs should be clickable means I can click and open a web page with a query results in a browser.

Due that encoded string contains hash(es) browser didn't open link correctly. Please read e.g. https://www.oho.com/blog/explained-60-seconds-hash-symbols-urls-and-seo

![2017-07-31 13_24_08-prometheus time series collection and processing server](https://user-images.githubusercontent.com/4910261/28776099-5e0e6386-75f5-11e7-807c-cc9da5bbb15a.jpg)

Correctly opened url has form (a query by analogy, not exactly the same): 

"http://<HOSTNAME>:9090/graph?g0.range_input=1h&g0.expr=(round((node_filesystem_free%7Bjob%3D%22nodes%22%2Cmountpoint!%3D%22%2Fvar%2Flib%2Fnfs%2Frpc_pipefs%22%7D+%2F+node_filesystem_size%7Bjob%3D%22nodes%22%7D+and+ON(device)+node_filesystem_readonly+!%3D+1)+*+100%2C+1)+%3E+10)+and+(round((node_filesystem_free%7Bjob%3D%22nodes%22%2Cmountpoint!%3D%22%2Fvar%2Flib%2Fnfs%2Frpc_pipefs%22%7D+%2F+node_filesystem_size%7Bjob%3D%22nodes%22%7D+and+ON(device)+node_filesystem_readonly+!%3D+1)+*+100%2C+1)+%3C+25)&g0.tab=0"

I've receive correct link by click like a green arrow shows.

![2017-07-31 13_41_06-prometheus time series collection and processing server](https://user-images.githubusercontent.com/4910261/28776281-46952806-75f6-11e7-86cc-f0f81c23cfdb.jpg)

**Comment by base698** [comment] 2019-10-31 22:52
My .GeneratorURL goes to a pod name, how do you change the name to it's domain name?  Is this a prometheus config option?

**Comment by base698** [comment] 2019-10-31 22:54
web.external-url in case anyone is looking for it :)

**Comment by simonpasquier** [comment] 2019-11-04 09:21
I failed to reproduce the issue with the most recent versions of Prometheus and Alertmanager. I'm closing the issue, feel free to reopen if needed.

**Closed by simonpasquier** 2019-11-04 09:21 UTC
Labels: area/usability, component/notify, kind/bug

**Comment by roidelapluie** [comment] 2021-04-28 09:58
Prometheus also has a web.external-url  flag.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
