### ISSUE TITLE
Sync delay on silenced alerts across all cluster

### ISSUE THREAD

**Issue by shirpx** [prometheus/alertmanager#1994] opened 2019-08-05 14:52 UTC
When adding a silenced alert it should sync across all cluster, the sync is slow and it can take between 15-20 minutes to the silenced alert to get to all the cluster peers.
it used to be a lot faster and sync right away.

the cluster seems healthy in 9093 status and all the peers connections established.

not seeing anything relevant in the logs about silences, those are the only logs regarding that:
level=info ts=2019-08-05T14:33:48.653694307Z caller=silence.go:269 component=silences msg="Running maintenance"
level=info ts=2019-08-05T14:33:48.659125972Z caller=silence.go:271 component=silences msg="Maintenance done" duration=5.437413ms size=5698

alertmanager_silences metric across all cluster:
<img width="1421" alt="Screen Shot 2019-08-05 at 17 52 08" src="https://user-images.githubusercontent.com/33197846/62473781-297ea600-b7aa-11e9-9457-63e26f768610.png">

**Environment**

* System information:
Linux 4.14.19-coreos x86_64

* Alertmanager version:
v0.14.0

* Prometheus version:
v2.3.1

**Comment by simonpasquier** [comment] 2019-08-06 08:14
> Alertmanager version: v0.14.0

Is it really the version you're running? It is more than a year ago and the clustering/replication uses a different library now.

**Comment by simonpasquier** [comment] 2019-08-27 14:55
Closing since 0.14 isn't supported by any means. Feel free to re-open if you can reproduce with the latest AlertManager version.

**Closed by simonpasquier** 2019-08-27 14:55 UTC
Labels: kind/more-info-needed
