### ISSUE TITLE
alertmanger doesn't send mail when alert.

### ISSUE THREAD

**Issue by huyujie** [prometheus/alertmanager#908] opened 2017-07-16 13:50 UTC
This is my simple.yml in alertmanger:
global:
  smtp_smarthost: 'smtp.***.com:587'
  smtp_from: '***'
  smtp_auth_username: '***'
  smtp_auth_password: ******
  smtp_require_tls: true

route:
  group_by: ['alertname']
  receiver: team-X-mails

receivers:
- name: 'team-X-mails'
  email_configs:
  - to: '****@qq.com'
    send_resolved: true

and the log is:
Jul 16 21:32:39 i-7un8vy31 alertmanager[23045]: time="2017-07-16T21:32:39+08:00" level=info msg="running maintenance" component=nflog source="nflog.go:286"
Jul 16 21:32:39 i-7un8vy31 alertmanager[23045]: time="2017-07-16T21:32:39+08:00" level=info msg="running maintenance" component=silences source="silence.go:232"
Jul 16 21:32:39 i-7un8vy31 alertmanager[23045]: time="2017-07-16T21:32:39+08:00" level=info msg="maintenance done" component=nflog duration=113.161µs source="nflog.go:303"
Jul 16 21:32:39 i-7un8vy31 alertmanager[23045]: time="2017-07-16T21:32:39+08:00" level=info msg="maintenance done" component=silences duration=61.252µs source="silence.go:249"
Jul 16 21:38:13 i-7un8vy31 alertmanager[23045]: [224B blob data]

and the alert web has alarm:

summary: | Instance CPU usage is dangerously high
This device's CPU usage has exceeded the threshold with a value of 99.76666666674039.

**Comment by jessebolson** [comment] 2017-07-20 16:18
Config looks fine I think (hard to tell without code-block formatting). Mine for reference:

```
global:
  smtp_require_tls: false
  smtp_smarthost: smtpserver.example.com:25
  smtp_from: alertmanager@example.com

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: mail

receivers:
- name: 'mail'
  email_configs:
  - to: me@example.com
```

Is an SMTP request being sent from your Prometheus server to the SMTP server? Use tcpdump if you can. Otherwise, check your SMTP logs - maybe there's something of interest over there. In any case, I doubt the problem is Prometheus if your config is fine.

**Comment by stuartnelson3** [comment] 2017-07-21 08:25
You're connecting on port `587` with `tls`, and from looking at the code, it appears we are only making a `tls` connection when the port is `465`.

https://github.com/prometheus/alertmanager/blob/a566036015c0cfd1bf218b5de922e57cfa623999/notify/impl.go#L274-L290

After doing a bit of reading at http://blog.mailgun.com/25-465-587-what-port-should-i-use/, it seems we should be focusing on port `587` and allowing TLS there.

Can you check logs to confirm? I'm guessing the email is being sent, but your server is rejecting it because no TLS connection is being made.

**Comment by jessebolson** [comment] 2017-07-21 14:24
@stuartnelson3

I have a similar (almost exact) config at home that works without problem utilizing port 587 and tls. 

‘’’
global:
  resolve_timeout: 5m
  smtp_from: alertmanager@example.com
  smtp_smarthost: mail.example.com:587
  smtp_auth_username: jesse@example.com
  smtp_auth_password: <secret>
  smtp_auth_secret: null
  smtp_auth_identity: ""
  smtp_require_tls: true
‘’’

I’m using the latest 2.0 beta.

**Comment by stuartnelson3** [comment] 2017-07-22 07:04
Ah k, thanks for clarifying. Your previous post had `smpt_require_tls: false`.

**Comment by jessebolson** [comment] 2017-07-22 16:37
Nah, my apologies - I should’ve posted a more similar config to begin with.@huyujie any luck with finding logs?

**Comment by mxinden** [comment] 2017-07-27 15:08
Thanks for reporting @huyujie. I am closing here, as I am interpreting from the missing response that this has been fixed. Please feel free to reopen.

**Closed by mxinden** 2017-07-27 15:08 UTC

**Comment by djooee** [comment] 2018-05-29 15:05
This is my simple.yml in alertmanger:
global:
  resolve_timeout: 5m
  smtp_from: ****@***.com
  smtp_smarthost: 'smtp.***.com:25'
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: aaa
  group_by:
  - alertname
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
receivers:
- name: aaa
  email_configs:
  - send_resolved: false
    to: *****@****.com
    from: ****@****.com
    smarthost: *****:25
    headers:
      From: ****@****.com
      Subject: '{{ template "email.default.subject" . }}'
      To: ****@****.com
    html: '{{ template "email.default.html" . }}'
    require_tls: true
  webhook_configs:
  - send_resolved: true
    url: http://********
templates: []

but alertmanger doesn't send mail when alert. 
thanks
