### ISSUE TITLE
panic: runtime error found at log on v 0.04

### ISSUE THREAD

**Issue by changwuf31** [prometheus/alertmanager#182] opened 2015-12-08 08:25 UTC
Found this on log file:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4e532d]

goroutine 15 [running]:
github.com/prometheus/alertmanager/manager.(*memoryAlertManager).removeExpiredAggregates(0xc2080c3cc0)
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/.build/gopath/src/github.com/prometheus/alertmanager/manager/manager.go:282 +0x23d
github.com/prometheus/alertmanager/manager.(*memoryAlertManager).runIteration(0xc2080c3cc0)
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/.build/gopath/src/github.com/prometheus/alertmanager/manager/manager.go:395 +0x33
github.com/prometheus/alertmanager/manager.(*memoryAlertManager).Run(0xc2080c3cc0)
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/.build/gopath/src/github.com/prometheus/alertmanager/manager/manager.go:408 +0x9a
created by main.main
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/main.go:111 +0xd50

goroutine 1 [chan receive, 12 minutes]:
github.com/prometheus/alertmanager/manager.(*notifier).Dispatch(0xc208114600)
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/.build/gopath/src/github.com/prometheus/alertmanager/manager/notifier.go:813 +0x54
main.main()
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/main.go:157 +0x15c0

goroutine 14 [chan receive]:
main.func·001()
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/main.go:85 +0x84
created by main.main
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/main.go:90 +0x659

goroutine 16 [IO wait]:
net.(*pollDesc).Wait(0xc208110f40, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208110f40, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208110ee0, 0x0, 0x7f9d6309edf0, 0xc2080f1bf8)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20802c5f0, 0x63aa9e, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc20802c5f0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc20805a960, 0x7f9d630a1698, 0xc20802c5f0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc20805a960, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0x90aff0, 0x5, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1808 +0xba
github.com/prometheus/alertmanager/web.WebService.ServeForever(0xc2081145d0, 0xc208114690, 0xc208074980, 0xc2081180f0, 0x90aff0, 0x5, 0xc208029be0, 0x8, 0x0, 0x0)
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/.build/gopath/src/github.com/prometheus/alertmanager/web/web.go:78 +0x8e6
created by main.main
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/main.go:145 +0x12f1

goroutine 17 [select, 13 minutes]:
github.com/prometheus/alertmanager/config.(*fileWatcher).Watch(0xc20811e480, 0xc208114720)
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/.build/gopath/src/github.com/prometheus/alertmanager/config/watcher.go:49 +0x8fb
created by main.main
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/main.go:154 +0x14b0

goroutine 19 [syscall, 13 minutes]:
syscall.Syscall(0x0, 0x3, 0xc208187ee0, 0x10000, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x3, 0xc208187ee0, 0x10000, 0x10000, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x3, 0xc208187ee0, 0x10000, 0x10000, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:136 +0x58
gopkg.in/fsnotify%2ev0.(*Watcher).readEvents(0xc20805a5a0)
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/.build/gopath/src/gopkg.in/fsnotify.v0/fsnotify_linux.go:219 +0x12c
created by gopkg.in/fsnotify%2ev0.NewWatcher
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/.build/gopath/src/gopkg.in/fsnotify.v0/fsnotify_linux.go:126 +0x420

goroutine 20 [chan receive, 13 minutes]:
gopkg.in/fsnotify%2ev0.(*Watcher).purgeEvents(0xc20805a5a0)
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/.build/gopath/src/gopkg.in/fsnotify.v0/fsnotify.go:21 +0x55
created by gopkg.in/fsnotify%2ev0.NewWatcher
        /home/julius/gosrc/src/github.com/prometheus/alertmanager/.build/gopath/src/gopkg.in/fsnotify.v0/fsnotify_linux.go:127 +0x43a
```

**Comment by fabxc** [comment] 2015-12-08 09:12
Duplicate of #122.
The master branch includes a fix for that.

**Closed by fabxc** 2015-12-08 09:12 UTC
