### ISSUE TITLE
Slack channel integration: vmalertmanager got unexpected status code 429

### ISSUE THREAD

**Issue by vvxxvvxx** [prometheus/alertmanager#3189] opened 2022-12-22 10:44 UTC
**What did you do?**
During the victoria metrics upgrade, we see lots of alerts being fired to our slack channel and resolved. but querying using the alert expression are good and should have no alerts expected. During this process, we see there are many below errors in the vmalertmanager pod logs.
```
ts=2022-12-22T08:35:00.761Z caller=dispatch.go:354 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="slack-stage/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"slackchannel-alerts-stage\": unexpected status code 429: {\"retry_after\":1,\"ok\":false,\"error\":\"rate_limited\"}"
ts=2022-12-22T08:35:00.773Z caller=dispatch.go:354 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="slack-stage/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"slackchannel-alerts-stage\": unexpected status code 429: {\"retry_after\":1,\"ok\":false,\"error\":\"rate_limited\"}"
ts=2022-12-22T08:35:00.784Z caller=dispatch.go:354 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="slack-stage/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"slackchannel-alerts-stage\": unexpected status code 429: {\"retry_after\":1,\"ok\":false,\"error\":\"rate_limited\"}"
ts=2022-12-22T08:35:00.789Z caller=dispatch.go:354 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="slack-stage/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"slackchannel-alerts-stage\": unexpected status code 429: {\"retry_after\":1,\"ok\":false,\"error\":\"rate_limited\"}"
ts=2022-12-22T08:35:02.121Z caller=dispatch.go:354 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="slack-stage/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"slackchannel-alerts-stage\": unexpected status code 429: {\"retry_after\":1,\"ok\":false,\"error\":\"rate_limited\"}"
```

vmalertmanager version: v0.24.0

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version: v0.24.0

	insert output of `alertmanager --version` here (repeat for each alertmanager
	version in your cluster, if relevant to the issue)

* Prometheus version:

	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)

* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by vvxxvvxx** [comment] 2022-12-23 00:21
@roidelapluie @simonpasquier Could you please also take a look?

**Comment by simonpasquier** [comment] 2022-12-23 10:04
I think that it is a duplicate of #2205

**Closed by simonpasquier** 2022-12-23 10:04 UTC
