### ISSUE TITLE
UI: Regexp checkbox not selectable in Firefox

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#436] opened 2016-07-20 17:02 UTC
In Firefox, when you click the regexp checkbox in the silence form, nothing happens.

**Comment by beorn7** [comment] 2016-07-20 17:03
@astera here you can check the progress on the issue discussed.

**Comment by fabxc** [comment] 2016-08-08 08:14
I know this is not a solution, but does tab-ing and hitting space work in the meantime?

**Comment by beorn7** [comment] 2016-08-15 11:10
While the checkbox seems to be in the tab cycle, it is neither highlighted in any way while focused, nor does it react to hitting space.

**Comment by grobie** [comment] 2016-09-01 00:04
@beorn7 Can you test again? Works for me in Firefox.

**Comment by astera** [comment] 2016-09-01 06:37
@grobie What happens (on my machine) currently is that in Firefox, you can edit a silence, and clicking the `Regex` checkbox makes it appear checked; however on hitting `UPDATE` to save any changes made, the setting is 'forgotten', and the value that should be a regular expression is assigned with an `=` instead of `=~`.

**Comment by grobie** [comment] 2016-09-01 12:09
I can confirm, even with Chrome. I'll fix it today and release v0.4.2.

**Comment by grobie** [comment] 2016-09-01 19:31
Will be released with v0.4.2.

**Closed by grobie** 2016-09-01 19:31 UTC
Labels: component/ui, kind/bug

**Comment by RRAlex** [comment] 2016-12-12 21:43
This seems to still be a problem in latest (0.5.1)

**Comment by brancz** [comment] 2016-12-12 21:53
@RRAlex it seems to be a new problem tracked here: https://github.com/prometheus/alertmanager/issues/565
