### ISSUE TITLE
alertmanager can't send email

### ISSUE THREAD

**Issue by navyabairi** [prometheus/alertmanager#1480] opened 2018-07-25 16:27 UTC
hello,

I'm working on setting up alertmanager on google cloud. 
I'm having the some issue with the alertmanager sending emails, but when I use mailx server, I'm getting email without any issue. please helm me with this

I'm using this command with mailx: 
echo -e 'hello' | mailx  -S ssl-verify=ignore -S smtp=smtps://smtpserver.com:2525 -S from="noreply@domain.com" -S ssl-verify=ignore -S nss-config-dir=/etc/pki/nssdb/ -s criticalalert -vv toaddress@domain.com

Below are the logs I'm getting on alertmanager:

`level=error ts=2018-07-25T16:16:28.992881815Z caller=dispatch.go:279 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err=EOF level=error ts=2018-07-25T16:16:28.992495571Z caller=notify.go:332 component=dispatcher msg="Error on notify" err=EOF level=error ts=2018-07-25T16:16:28.992960753Z caller=dispatch.go:279 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err=EOF level=error ts=2018-07-25T16:16:38.992955299Z caller=notify.go:332 component=dispatcher msg="Error on notify" err=EOF level=error ts=2018-07-25T16:16:38.993024946Z caller=dispatch.go:279 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err=EOF level=error ts=2018-07-25T16:16:38.992954963Z caller=notify.go:332 component=dispatcher msg="Error on notify" err=EOF level=error ts=2018-07-25T16:16:38.993125709Z caller=dispatch.go:279 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err=EOF`

Alertmanager config:

```
- name: 'email'
      email_configs:
      - to: 'toaddress@domain.com'
        send_resolved: true
        smarthost: 'smtp.server.com:2525'
        from: 'noreply@domain.com'
        require_tls: true
        text: 'mail-from-prometheus'
```

**Comment by stuartnelson3** [comment] 2018-07-25 16:43
This looks like a usage question, and would be better sent to prometheususers@googlegroups.com, where others could benefit from reading this.

The error is an EOF, which I'm guessing is something about communicating with your mail server.

Is this request being sent against a strict ssl port? `require_tls` is for tls and not ssl connections.

**Comment by stuartnelson3** [comment] 2018-07-25 16:48
You can test this with `openssl s_client -connect smtpserver.com:2525`. If it is successful then your endpoint is speaking `ssl`, and we are sending an initial `EHLO` before attempting to upgrade with `start_tls`.

**Comment by navyabairi** [comment] 2018-07-25 18:42
I tried `openssl s_client -connect smtpserver.com:2525` this earlier, it is showing the output as connected. Is it possible to configure ssl on alertmanager email_config? I couldn't find any doc regarding this.

**Comment by vikas027** [comment] 2018-07-28 00:02
@navyabairi  Can you send an email from the local server?

Maybe try this command and check logs `/var/log/mail.log` (for Ubuntu)
```bash
echo "Test Email" | mail -s "Mail Subject" <your_email_id>
```

**Comment by sipian** [comment] 2018-08-15 17:50
@simonpasquier 
Is the plan to add SSL support in [email Notify](https://github.com/prometheus/alertmanager/blob/master/notify/impl.go#L258) function?

**Comment by simonpasquier** [comment] 2019-07-16 09:52
Closing as there's no evidence that the problem is with AlertManager.

**Closed by simonpasquier** 2019-07-16 09:52 UTC
Labels: component/notify, kind/support

**Comment by datadogmandal** [comment] 2019-08-05 11:19
Aug 05 16:43:38 techops-rnd-srv alertmanager[20810]: level=error ts=2019-08-05T11:13:38.120838784Z caller=dispatch.go:177 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="sending mail from: 530 5.7.0 Must issue a STARTTLS command first. q4sm15660922pjq.27 - gsmtp"

**Comment by datadogmandal** [comment] 2019-08-05 11:20
I am getting below error in alert manager 

Aug 05 16:43:38 techops-rnd-srv alertmanager[20810]: level=error ts=2019-08-05T11:13:38.120838784Z caller=dispatch.go:177 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="sending mail from: 530 5.7.0 Must issue a STARTTLS command first. q4sm15660922pjq.27 - gsmtp"


please help below is the configruration of alertmanager.yml

global:
  smtp_smarthost: smtp.googlemail.com:587
  smtp_from: alertmanager@example.com
  smtp_require_tls: false

route:
  receiver: default.receiver
  routes:
  - match:
      service: example.service
    receiver: example.receiver
    continue: true

receivers:
- name: default.receiver
  email_configs:
    - to: dhruba.mandal@one97.net
- name: example.receiver
  email_configs:
    - to: dhruvmandal@gmail.com

**Comment by DanielChuDC** [comment] 2019-12-04 10:54
Hi any update?

**Comment by DanielChuDC** [comment] 2019-12-04 11:01
ok, I am able to resolve this issue based on this article
https://www.digitalocean.com/community/questions/send-email-using-gmail-smtp

change the `smarthost` under `email_configs` from
```

smarthost: smtp.gmail.com:587 

```

to  

```
smarthost: ssl://smtp.gmail.com:456
```

Hope it helps!

**Comment by XI1062-abhisheksinghal** [comment] 2020-12-31 15:00
I am to facing the same issue , tries using smarthost: ssl://smtp.gmail.com:456 but now its says to many : "colon's" any suggestion on how to resolve it ?

**Comment by AshishJainMSRIT** [comment] 2021-07-19 12:13
> I am to facing the same issue , tries using smarthost: ssl://smtp.gmail.com:456 but now its says to many : "colon's" any suggestion on how to resolve it ?

I am facing the same issue. How to resolve this?

**Comment by WhiteHatTux** [comment] 2021-09-24 01:44
Although this is kind of old I wanted to add my solution: 
I was trying to use the **smtp-relay**.gmail.com:25 and would get `caller=notify.go:724 component=dispatcher receiver=gmail-notification integration=email[0] msg="Notify attempt failed, will retry later" attempts=1 err="send EHLO command: EOF"` 
The solution was to set the global.smtp_hello: to <mydoimain.com>
Otherwise the connection did not work. 
I know this is not the specific error you had, but google still brought me here with my exception. :-)

**Comment by cmantsch** [comment] 2022-05-12 08:20
Thanks @WhiteHatTux, this fixed it for me! Seems like google changed some stuff on the smtp (though it only occurred for me recently, worked fine before)
