### ISSUE TITLE
feat(api): expose alert groups in the API

### ISSUE THREAD

**Issue by prymitive** [prometheus/alertmanager#1712] opened 2019-01-16 15:36 UTC
`/api/v1/alerts/groups` was removed via #1525 and there's no equivalent for `/api/v2`.
Having alerts accessible via the API with all the grouping information is useful if the intent is to consume alert information the same way it's grouped in notifications.
There is already some context given on #868 why would this be useful for alertmanager UI.
Due to flexibility of the routing logic it's quite complex to recreate same grouping outside of alertmanager, even if full routing config is known, hence the request to (re)add it to the API.

Related issues with additional context:
#868
prymitive/karma#115
#1694

**Comment by beorn7** [comment] 2019-02-05 13:07
IMHO, this is a duplicate of #868. The latter should give you exactly what you need.

**Comment by prymitive** [comment] 2019-02-05 13:17
I think it's only a dup if #866 would be solved by adding a version of `/api/v1/alerts/groups`, that ticket talks also about the UI and I wasn't sure if there was any consensus yet of how is that going to be resolved and implemented, hence this ticket with a specific request.

If [this suggestion](https://github.com/prometheus/alertmanager/issues/868#issuecomment-309076761) is going to end up in alertmanager API (`groupIDs` field) and there will be a way to fetch group information (like the receiver it used and group_by labels) then I'm happy to close it as a dup as I *think* it would be all that I need.

**Comment by beorn7** [comment] 2019-02-05 14:01
I think that's exactly what we need for #866.

The UI is entirely backed by API calls, so if AM's own UI can display the groups, the API has to support it, too.

**Closed by beorn7** 2019-02-05 14:01 UTC
