### ISSUE TITLE
The prometheus resolved alarm message does not correctly display the correct value of the current indicator, but displays the value of the last evaluation period.

### ISSUE THREAD

**Issue by ckyx** [prometheus/alertmanager#1485] opened 2018-07-28 06:12 UTC
The prometheus resolved alarm message does not correctly display the correct value of the current indicator, but instead displays the value of the last evaluation period. And the value in the resolved message is greater than the set threshold.

**Comment by hoffie** [comment] 2018-07-28 09:52
By design, this seems to be how it is supposed to be:
https://groups.google.com/forum/#!searchin/prometheus-users/alert$20resolved$20value|sort:date/prometheus-users/oc2fHcSY5UA/ilbVuQbpAAAJ
https://groups.google.com/forum/#!searchin/prometheus-users/alert$20resolved$20value|sort:date/prometheus-users/b9_yscNUdFE/SEEMm_NtAAAJ
https://groups.google.com/forum/#!searchin/prometheus-users/alert$20resolved$20value|sort:date/prometheus-users/QV7el8b4lI4/H1x7Yim9AAAJ

Prometheus will no longer send an alert when the alert condition no longer triggers.
This is what makes Alertmanager send the resolved message. Alertmanager by itself has no other means of querying for the current (non-firing) value.

**Comment by simonpasquier** [comment] 2018-07-30 09:30
I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Closed by simonpasquier** 2018-07-30 09:30 UTC
