### ISSUE TITLE
prometheus dont support use labels of rule in annotations?

### ISSUE THREAD

**Issue by szediktam** [prometheus/alertmanager#1831] opened 2019-04-11 09:52 UTC
I create a prometheus alerting rule as following:
```
alert: cluster_cpu_alarm
expr: cluster_cpu_utilization  > 0.90
for: 1m
labels:
  severity: Medium
  cluster: dev
annotations:
  summary: the cpu utilization of cluster {{ $labels.cluster }} is more than 90%, now {{ $value }}.
```

When the alert is triggered to alertmanager, the {{ $labels.cluster }} in annotations.summary is empty, and {{ $value }} is a real cpu utilization.
Prometheus donot support use labels of alertingrule in annotations? 

@brancz

**Comment by brancz** [comment] 2019-04-11 09:57
If you define the label in the alert definition, why can't you use it in the annotation?

Generally speaking though for what you're trying to achieve here, I'd suggest to add an external label to your Prometheus server configured with `cluster: dev`, then the firing alerts will have that label and you can use it in the annotation.

**Comment by szediktam** [comment] 2019-04-11 10:16
That means prometheus dont support use labels in annotations like {{ $labels.cluster }}?

the labels are different for different application, I can not put them on expr. So I want to define many labels in alertingrules, and use it in annotations. I think it is a general usage.

**Comment by szediktam** [comment] 2019-04-11 11:37
> If you define the label in the alert definition, why can't you use it in the annotation?
> 
> Generally speaking though for what you're trying to achieve here, I'd suggest to add an external label to your Prometheus server configured with `cluster: dev`, then the firing alerts will have that label and you can use it in the annotation.

**Comment by simonpasquier** [comment] 2019-04-11 12:00
This issue relates to Prometheus, not Alermanager. It is also a dupe of https://github.com/prometheus/prometheus/issues/5405

**Closed by simonpasquier** 2019-04-11 12:00 UTC

**Comment by xiaozongyang** [comment] 2020-12-01 04:50
Hi @szediktam,
I've got the same issues as yours, would you mind sharing some information about this? Did you solve it by some configurations, or whatever?
