### ISSUE TITLE
New UI can't load script.js when using "-web.external-url".

### ISSUE THREAD

**Issue by Jean-Daniel** [prometheus/alertmanager#834] opened 2017-05-30 12:05 UTC
I just installed alter manager 0.7.0-rc0 and start it using `-web.external-url=http://example.com/alerts/`, but when I load the UI in the browser, it tries to load '/script.js' and failed with a 404 error. 

The UI should either use relative path or respect the path specified by `-web.external-url` when loading resources.

**Comment by stuartnelson3** [comment] 2017-05-30 13:08
Thanks for the report! We have an issue tracking this (but I can't seem to find it right now ...). The fix will hopefully be included soon.

**Comment by mxinden** [comment] 2017-05-30 14:56
As far as I can tell this is a duplicate of #323. It is part of the 0.7 milestone. I will close here, please reopen if I am mistaking.

**Closed by mxinden** 2017-05-30 14:56 UTC
