### ISSUE TITLE
Allow deep-linking into alertmanager alert list

### ISSUE THREAD

**Issue by mpalmer** [prometheus/alertmanager#438] opened 2016-07-26 04:27 UTC
I'd like to be able to link to the list of alerts of a given alert name from the notifications I send.  At the moment, there's no element more specific than `#alert-groups` with an ID, so I can't link to anything specific, forcing people to scroll/search to find the relevant items.  An ID on each `.alert-group` div along the lines of `alertname-<foo>` would be perfect.

**Comment by grobie** [comment] 2016-09-01 00:06
Duplicate of #211

**Closed by grobie** 2016-09-01 00:06 UTC
Labels: component/ui, kind/enhancement
