### ISSUE TITLE
v0.6.1 severe malfunction.

### ISSUE THREAD

**Issue by raypettersen** [prometheus/alertmanager#770] opened 2017-05-04 13:07 UTC
We upgraded alertmanager today, and experienced severe problems in the GUI. For example, it seems the previous version had some javascripting cached so the rendering was way off. After testing in incognito, it was somewhat better, but we ran into some weird bugs. For example, when clicking "hide silences", the actual view updated and _showed_ the silences. The exact opposite behavior that was expected. Also, the silence icon was gone so we had no idea of knowing what alarm was silenced or not. We eventually downgraded as we were having so many issues that we didn't dare running this release in production.

Has anyone else experienced the same issues?

**Comment by raypettersen** [comment] 2017-05-04 13:19
`ime="2017-05-04T13:35:37+02:00" level=warning msg="Could not get file: AssetInfo ui/lib/angular-sanitize.min.js.map not found" source="web.go:31"`
`time="2017-05-04T13:35:37+02:00" level=warning msg="Could not get file: AssetInfo ui/lib/jquery.min.map not found" source="web.go:31" `
`time="2017-05-04T13:35:37+02:00" level=warning msg="Could not get file: AssetInfo ui/lib/angular.min.js.map not found" source="web.go:31" `
`time="2017-05-04T13:35:37+02:00" level=warning msg="Could not get file: AssetInfo ui/lib/angular-route.min.js.map not found" source="web.go:31" `
`time="2017-05-04T13:35:37+02:00" level=warning msg="Could not get file: AssetInfo ui/lib/angular-resource.min.js.map not found" source="web.go:31" `
`time="2017-05-04T13:35:37+02:00" level=warning msg="Could not get file: AssetInfo ui/lib/angular-moment.min.js.map not found" source="web.go:31" `
`time="2017-05-04T13:35:40+02:00" level=warning msg="Could not get file: AssetInfo ui/lib/jquery.min.map not found" source="web.go:31"`

![selection_804](https://cloud.githubusercontent.com/assets/7197374/25705243/ef4402a6-30dc-11e7-83b1-c17fa9f59aff.png)

![selection_802](https://cloud.githubusercontent.com/assets/7197374/25705275/0542e04a-30dd-11e7-88b8-14bbe00b3e58.png)

**Comment by fabxc** [comment] 2017-05-05 14:15
The logging of `.map` files not being found is normal. That usually happens when you open the dev console in your browser, which than tries to get a `.js.map` file for every `.js` file that was loaded.

Otherwise, I cannot report similar behavior. I've been switching between different versions multiple times.
On the silencing issue, @stuartnelson3 @mxinden can you check again that https://github.com/prometheus/alertmanager/commit/6a909abf17d56a09ade3ad6753b5eb844fe5b244 this was all correct.

It honestly sounds more like Internet Explorer (assuming based on the screenshot) to behave very differently in terms of JS caching and even loading cached stuff in incognito mode maybe? Something we should address (and do in the new UI afaik), but wouldn't classify it as severe malfunction.

**Comment by raypettersen** [comment] 2017-05-05 14:23
Testing was done on both chrome, firefox and IE. We tested with windows, linux, and mac. Gui was all over the place.

**Comment by fabxc** [comment] 2017-05-05 14:25
Mh, interesting. Thanks for the update. I tried multiple browsers and switching various AM versions now as well but couldn't reproduce yet.

What distribution of the version are you running? Docker, Tarballs, compiled yourself?

**Comment by raypettersen** [comment] 2017-05-05 14:29
We're using the tar balls, and bundling them into rpms. From what you're saying, it leads me to think that something went wrong in our end. I'll do some more checking over the weekend.

**Comment by fabxc** [comment] 2017-05-05 14:31
Will try again with tarballs rather than compiling it myself. I don't think your RPM packaging could be a cause. The javascripts and HTML files are compiled directly into the binary.

**Comment by mxinden** [comment] 2017-05-05 14:32
@fabxc @raypettersen I am not able to reproduce the issues either with a self compiled version of 6a909abf17d56a09ade3ad6753b5eb844fe5b244.

**Comment by raypettersen** [comment] 2017-05-05 14:36
Thanks for the input. We're running behind nat and using external path option. Could that be the issue?

**Comment by fabxc** [comment] 2017-05-05 14:39
There are many ways how this could cause problems. However, returning to the previous version resolves the problem, right?

**Comment by raypettersen** [comment] 2017-05-05 14:43
Reverting to 0.4.2 resolves everything.

**Comment by fabxc** [comment] 2017-05-05 15:02
Can't reproduce the issue of JS not loading properly at all but some of the silence-related ones. Trying to track it down.

**Comment by raypettersen** [comment] 2017-05-09 12:08
Seems like this issue is under control. Will we see another release soon? We're holding off upgrading at the time being.

**Comment by mxinden** [comment] 2017-05-09 13:10
@raypettersen You can find the new release [here](https://github.com/prometheus/alertmanager/releases/tag/v0.6.2). Thanks for the help!

**Comment by raypettersen** [comment] 2017-05-09 13:12
Superb. I'll test the release tomorrow. Thanks!

**Comment by mxinden** [comment] 2017-05-09 13:40
Closing here. Please feel free to reach out to us again.

**Closed by mxinden** 2017-05-09 13:40 UTC
