### ISSUE TITLE
New annotations not reflected in UI or webhook pushes

### ISSUE THREAD

**Issue by ipstatic** [prometheus/alertmanager#534] opened 2016-10-14 20:03 UTC
While testing the webhook functionality we added a new annotation to a rule and reloaded Prometheus. Prometheus' alert page shows the new annotation, however the AM UI nor the JSON data provided in the webhook show the new annotation. Is this expected?

**Comment by fabxc** [comment] 2016-11-18 15:33
After Prometheus has resent the alert to Alertmanager, the annotation should be updated there.
Testing this with a running Alertmanager and curl is working as expected in the UI for me.

```bash
curl -XPOST -d'[{"labels":{"alertname":"a"},"annotations":{"a":"123"}}]' http://localhost:9093/api/v1/alerts
curl -XPOST -d'[{"labels":{"alertname":"a"},"annotations":{"a":"123456"}}]' http://localhost:9093/api/v1/alerts
```

Can you provide steps to reproduce the problem?

**Comment by ipstatic** [comment] 2016-11-23 04:05
Sorry for my delay. Maybe this is an issue with Prometheus itself. To reproduce do the following:

1. Run Prometheus with a simple alert rule and point it to an AM instance
2. While the alert is firing, add or remove an annotation
3. Reload Prometheus
4. You will now see the new annotations reflected in the UI of Prometheus however you will not see the new annotations reflected in the Alertmanager UI.

**Comment by brian-brazil** [comment] 2016-11-23 05:38
Dupe of #550 which was just fixed in Prometheus.

**Closed by brian-brazil** 2016-11-23 05:38 UTC
