### ISSUE TITLE
Feature request: stop silence on status change

### ISSUE THREAD

**Issue by sachaz** [prometheus/alertmanager#2148] opened 2019-12-19 18:26 UTC
Dear all,

as seen on old school supervision tools, a feature was to have a silence like who stops when the status of the alert changes.
For example: a failed status is silenced, when it's fixed the silence stops too.

**Comment by brian-brazil** [comment] 2019-12-19 18:36
Dupe of #1057

**Closed by brian-brazil** 2019-12-19 18:36 UTC
