### ISSUE TITLE
Update docs to note api/v1 deprecation and removal

### ISSUE THREAD

**Issue by ericrrath** [prometheus/alertmanager#3838] opened 2024-05-10 15:31 UTC
**What did you do?**
I read the [docs for 0.27.0](https://prometheus.io/docs/alerting/0.27/clients/) and found:
> The Alertmanager has two APIs, v1 and v2, both listening for alerts. The scheme for v1 is described in the code snipped below. The scheme for v2 is specified as an OpenAPI specification that can be found in the [Alertmanager repository](https://github.com/prometheus/alertmanager/blob/master/api/v2/openapi.yaml).

**What did you expect to see?**
I expected to see a note that `api/v1` has been deprecated and removed (due to commit b4f7027), and that all clients should now use `api/v2`.

**What did you see instead? Under which circumstances?**
I read the above description of both `api/v1` and `api/v2` as viable APIs.

**Environment**

Browser

* System information:

	N/A

* Alertmanager version:

	0.27.0

* Prometheus version:

	N/A

* Alertmanager configuration file:

	N/A

* Prometheus configuration file:

	N/A

* Logs:

	N/A

**Comment by TheMeier** [comment] 2024-05-11 14:00
Duplicate of https://github.com/prometheus/alertmanager/issues/3814, fixed in https://github.com/prometheus/alertmanager/pull/3815

**Closed** 2024-05-14 20:35 UTC
