### ISSUE TITLE
export configuration as plain text with secrets?

### ISSUE THREAD

**Issue by zetaab** [prometheus/alertmanager#2004] opened 2019-08-20 09:05 UTC
I am trying to export alertmanager configuration as plain text, because I am inserting it to kubernetes configmap. The problem is that when I marshal/unmarshal things the secrets are replaced with `<secret>`. Is there any way to avoid removing secrets from the configuration.

Example
```
	alertmanager := &config.Config{
		Receivers: []*config.Receiver{
			{
				Name: "kapi",
				WebhookConfigs: []*config.WebhookConfig{
					{
						NotifierConfig: config.NotifierConfig{
							VSendResolved: true,
						},
						HTTPConfig: &commoncfg.HTTPClientConfig{
							BearerToken: commoncfg.Secret("placeholder"),
						},
						URL: &config.URL{URL: "https://google.fi"},
					},
				},
			},
		},
		Route: &config.Route{
			Receiver:       "kapi",
			RepeatInterval: &dur,
		},
	}
```

alertmanager.String() will produce:

```
        route:
          receiver: kapi
          repeat_interval: 1d
        receivers:
        - name: kapi
          webhook_configs:
          - send_resolved: true
            http_config:
              bearer_token: <secret>
            url: https://google.fi
        templates: []
```

instead I would like to have
```
        route:
          receiver: kapi
          repeat_interval: 1d
        receivers:
        - name: kapi
          webhook_configs:
          - send_resolved: true
            http_config:
              bearer_token: placeholder
            url: https://google.fi
        templates: []
```

Of course I can run `strings.Replace(alertmanager.String(), "<secret>", "placeholder", -1)`. However, the problem starts when there are multiple secrets in configuration.

**Comment by mxinden** [comment] 2019-08-20 10:08
Hi @zetaab,

You might find some answers in https://github.com/prometheus/alertmanager/issues/1985 and https://github.com/prometheus/alertmanager/issues/1985.

**Comment by brian-brazil** [comment] 2019-08-20 10:32
You could work from the file on disk.

**Comment by simonpasquier** [comment] 2019-08-27 14:53
Closing as a duplicate of #1985.

**Closed by simonpasquier** 2019-08-27 14:53 UTC

**Comment by zetaab** [comment] 2019-09-03 12:44
@brian-brazil do you have tip for that? I tried following

```
	alertmanager := &config.Config{
		Receivers: []*config.Receiver{
			{
				Name:           "kapi",
				WebhookConfigs: webconfigs,
				SlackConfigs:   slackconfigs,
			},
		},
		Route: &config.Route{
			Receiver:       "kapi",
			RepeatInterval: &dur,
		},
	}

	// write to disk
	dir, err := ioutil.TempDir("", "alertmanager")
	if err != nil {
		return "", err
	}
	defer os.RemoveAll(dir)

	newpath := filepath.Join(dir, "alertmanager.cfg")
	err = os.MkdirAll(filepath.Dir(newpath), os.ModePerm)
	if err != nil {
		glog.Errorf("error creating directory to %v", err)
		return "", err
	}

	jsonValue, err := json.Marshal(alertmanager)
	if err != nil {
		glog.Errorf("Marshal error %v", err)
		return "", err
	}

	err = ioutil.WriteFile(newpath, []byte(jsonValue), 0644)
	if err != nil {
		glog.Errorf("error writing to %s %v", newpath, err)
		return "", err
	}
```

but the problem is that in file its still `<secret>`
