### ISSUE TITLE
Silence form escapes backslashes, leading to double-escaping and thus unintended regexp's

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#1679] opened 2018-12-20 16:37 UTC
**What did you do?**

Created a silence with a regexp matcher that needs to match a literal `.`, which thus needs escaping.

**What did you expect to see?**

A regexp matcher matching the literal `.`.

**What did you see instead? Under which circumstances?**

The regexp got double-escaped, i.e. instead of `foo\.bar`, it became `foo\\.bar`, and thus matching a literal `\` followed by an arbitrary character.

Looking at the HTTP request sent by the UI, I can see the double-escaped parameter as `foo%5C%5C.bar`.

This makes it impossible to create silence regexp's matching literal `.` and similar.

Interestingly, creating a regexp matcher as a filter for the alerts page works just fine. Thus, I assume that's a subtle difference in how the UI is set up for the silence form vs. the matchers on the alerts page.

@stuartnelson3 was a bit puzzled by it. @mxinden and @w0rm , perhaps your Elm foo has something to say here?

**Environment**

* System information:

	Linux 4.4.10+soundcloud x86_64

* Alertmanager version:

	alertmanager, version 0.15.2 (branch: HEAD, revision: d19fae3bae451940b8470abb680cfdd59bfa7cfa)
	  build user:       root@3101e5b68a55
	  build date:       20180814-10:53:39
	  go version:       go1.10.3

**Comment by stuartnelson3** [comment] 2019-01-04 14:41
I spent more time looking at this and have no idea what's going on. As soon as a user enters `\` in the matcher value field, it is being sent to `UpdateMatcherValue` as `\\`. As far as I can tell, this appears to be getting added before we have any access to the value.

@w0rm any ideas?

**Comment by w0rm** [comment] 2019-01-04 21:57
I could not reproduce this locally, only in our production instance. The matcher is displayed with two backslashes for some reason, but when I click it, or edit the silence, it is a single backslash. 

API returns a single backslash too, so I think the issue is only when rendering a matcher button when viewing a silence.

![backslash](https://user-images.githubusercontent.com/43472/50713055-f9d0b980-1073-11e9-9132-f093e96dec30.gif)

**Comment by w0rm** [comment] 2019-01-04 22:02
This is how it looks locally, using the latest alertmanager from the master branch:

![backslash2](https://user-images.githubusercontent.com/43472/50713312-cc384000-1074-11e9-9406-ed2389996db9.gif)

**Comment by stuartnelson3** [comment] 2019-01-08 15:24
This appears to be fixed in master, but is a bug in 0.15.2

**Closed by stuartnelson3** 2019-01-08 15:24 UTC
Labels: area/usability, component/silences, component/ui, kind/bug, priority/P1

**Comment by beorn7** [comment] 2019-01-17 15:04
Verified that this works in 0.16.0-beta.0
