### ISSUE TITLE
Source-Button in dashboard doesn't lead to the alert source

### ISSUE THREAD

**Issue by max06** [prometheus/alertmanager#3450] opened 2023-08-08 12:14 UTC
**What did you do?**
I clicked the source-button next to an active alert.

**What did you expect to see?**
I expected to see a (new) page with a prometheus graph/table.

**What did you see instead? Under which circumstances?**
The alerts page on alertmanager did reload with all alerts collapsed.

**Environment**

* System information:

```
Linux 5.4.0-153-generic x86_64
Docker version 24.0.5, build ced0996
```        

* Alertmanager version:

```
alertmanager, version 0.25.0 (branch: HEAD, revision: 258fab7cdd551f2cf251ed0348f0ad7289aee789)
(using prom/alertmanager:v0.25.0)
```

* Prometheus version:

```
prometheus, version 2.46.0 (branch: HEAD, revision: cbb69e51423565ec40f46e74f4ff2dbb3b7fb4f0)
(using prom/prometheus:v2.46.0)
```

* Alertmanager configuration file:

```yaml
global:
  slack_api_url_file: '/etc/alertmanager/slack.url'

# The directory from which notification templates are read.
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# The root route on which each incoming alert enters.
route:
  group_by: ['alertname', 'cluster', 'service']
  receiver: slack
  repeat_interval: 24h
  group_wait: 45s
  group_interval: 5m
  routes:

receivers:
- name: slack
  slack_configs:
    - channel: '#monitoring'
      color: '{{ template "slack.color" . }}'
      title: '{{ template "slack.title" . }}'
      text: '{{ template "slack.text" . }}'
      send_resolved: true
      short_fields: true
      fields:
        - title: Hostname
          value: '{{ .CommonLabels._hostname }}'
        - title: IP
          value: '{{ .CommonLabels._ip }}'
        - title: Environment
          value: '{{ .CommonLabels._environment }}'
        - title: Zone
          value: '{{ .CommonLabels._node_az }}'


      actions:
        - type: button
          text: 'Runbook :green_book:'
          url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
        - type: button
          text: 'Query :mag:'
          url: '{{ (index .Alerts 0).GeneratorURL }}'
        - type: button
          text: 'Dashboard :chart_with_upwards_trend:'
          url: '{{ (index .Alerts 0).Annotations.dashboard_url }}'
        - type: button
          text: 'Silence :no_bell:'
          url: '{{ template "__alert_silence_link" . }}'
```

* Alertmanager commandline options:

```
      --config.file=/etc/alertmanager/alertmanager.yml
      --storage.path=/alertmanager
      --web.external-url=https://monitoring.somedomain.io/alertmanager
      --web.route-prefix=/

(traefik: traefik.http.middlewares.strip-alertmanager.stripprefix.prefixes: /alertmanager)
```

* Prometheus configuration file:

```
(not relevant)
```

* Logs:

```
(not relevant)
```

* Dashboard Infos

![image](https://github.com/prometheus/alertmanager/assets/7556827/388e216b-35a3-4172-9abf-04e73ceb0d6a)

(Active alert)

```html
<a class="btn btn-outline-info border-0" href="https://monitoring.somedomain.io/prometheus/graph?g0.expr=up+%3D%3D+0&amp;g0.tab=1"><i class="fa fa-line-chart mr-2"></i>Source</a>
```

(Source button next to the alert)

![image](https://github.com/prometheus/alertmanager/assets/7556827/4886f122-640e-41dc-a4b9-01e90b2525be)

(Click handler attached to said button). Removing this handler fixes the issue.

**Comment by simonpasquier** [comment] 2023-08-11 12:09
What is your browser? Can you share more details about the last screenshot with the handler?

**Comment by max06** [comment] 2023-08-11 12:16
Whoops, sorry. The screenshot was taken in Vivaldi 6.1 (chromium 114.0.5735.245) with the integrated devtools open. The screenshot shows the event listeners for a selected dom element.

![image](https://github.com/prometheus/alertmanager/assets/7556827/df8a8407-3e24-449e-8e5c-b1c37c67871e)

I'm afraid I can't show more of the contents without having to redact urls. 

If you need more details, I'd need more specific instructions - non-dev here 🥳

**Comment by simonpasquier** [comment] 2023-08-11 12:20
Can you try with another browser?

**Comment by max06** [comment] 2023-08-11 12:28
Yup. Verified in a clean vivaldi profile, in a regular chrome, in a virtual machine running firefox ESR and on a coworkers machine.

**Comment by simonpasquier** [comment] 2023-08-11 12:39
Hmm I can't reproduce on my side...

**Comment by max06** [comment] 2023-08-11 12:47
```gpg
-----BEGIN PGP MESSAGE-----
Version: BCPG v1.58

hQIMAwGQpmwKEPxPAQ/9HDaSF0pmfxRy0G6If92Vcwz4/Owh+RM3Gtv0+yTyR99B
MSD63YS4f0pqUXKGisbHKQ8OD3UAy4ZC0LquVRrXaPYT3puv9KuDffHCcHGwLPCD
bemTDTvmTpk6sK5J7uA39mwcc/ZJ0Ue9gE+ZIJtnwEXSIbpZ01PwpLbF4tGzBvYI
GAzwMswcUXzc5NtYBzOfiE3BYOOsG3wipDbagHuoh+Jx7sp00lUVhf53qHhCCNX6
jGqPGoMcnt+W9tS+0jl/+PaSCoaRgyEUKzIcglcumgjp5jNr7sFdnNg5AkCAXagJ
RSBf+WHLwSwDcMEdQbZLfgku2TAleDNgad1kg9RzR335N62vlKsRF10jMwTxrKjm
WhxlWy9HqM8rVltKl2AaoQMctG1VZ3yaZgBQ7ZsAIUoMuZgvIyrbt+oiHftdjwUf
Y6zTw1yapYWMdYok/nJ5BuxC9z6fYNlesj2d3VS9ivk1nD8pRvl3BnxFvhKmguA8
wORpHKp6p8Pe02PJOyPnrIA0EKvDqKIB76FuCGgKcJOJ1PKYXeogbjOz7rrCWI/P
cyU/+V9zTIIK7j2waIq7QtuqOTX29kJXs2PtvYCAqkNMMeWh5S/fUazR3NmfKzW7
d0F9Hu+Oa2hRBtDZRnrOCnjlUDOb5U3vMKNR9XcezrdofQuDy5emyHCgt1PYpnLS
kAFjYDQKP5ErQxOWRnOOeI3JFoDtvTfmkqzT+hqzJPO0t2BuqeNYaS5OtiEJRhpV
6fgV+o+7eLuOpKqJdOMwVd8VZhWtp3v+FqyYhIFW5/xb85pr69X7h2R1/RQK8rtS
mv7+E3ltCf+WDzbH599DULpoeck+u3zvOIDfbC+76JKZA0CFtWdzC6BHyqTnW7fg
zg==
=cNmA
-----END PGP MESSAGE-----
```

Encrypted using your public gpg key. Please keep the details hidden.

**Comment by TonyNoble** [comment] 2024-01-23 12:12
This is a duplicate of #1881 (unfixed) - the issue occurs when alertmanager and prometheus reside on the same domain

**Closed** 2024-01-23 12:40 UTC
Labels: component/ui
