### ISSUE TITLE
Alertmanager should have plugin system

### ISSUE THREAD

**Issue by onorua** [prometheus/alertmanager#1259] opened 2018-02-25 10:27 UTC
There are several integrations proposed, which were rejected due to reasons not really related to PR contents: 

https://github.com/prometheus/alertmanager/pull/709
https://github.com/prometheus/alertmanager/pull/601
https://github.com/prometheus/alertmanager/pull/700
https://github.com/prometheus/alertmanager/pull/600

There are more of them, those are just some from the list. 
Most rejections were due to some "plans" core maintainers had, which were never come to live, for several years already. Meanwhile [Grafana](https://github.com/grafana/grafana/tree/a69bdf9432c5559be093540d6744e6f15c63f832/pkg/services/alerting/notifiers) has 15 integrations already, even though main purpose of Grafana is to visualize things.

There is a proposal to create JSON unified interface inside core:
https://github.com/prometheus/alertmanager/issues/701
Which will not answer all the problems in the long run, as there will be more and more requests, and interfaces, and they will be rejected again due to something not related to functionality itself. 

That should not be the case, and already solved by many projects using plugins:
Hashicorp created: https://github.com/hashicorp/go-plugin which allows creating plugins in any language with gRPC support. 
Go has support support built in since 1.8 if I'm not mistaken. 

Plugin system will allow users to create plugins, which suite their needs, and as Hashicrop does already, can be even located in separate repo to share them among users. While if some plugin is not well maintained - can be removed from the default plugins list without affecting entire alert manager core functionality.

**Comment by brian-brazil** [comment] 2018-02-25 10:59
Dupe of #701

The webhook has existed for a long time, and is the standard way to integrations. It is not Go specific, and does not require us to manage plugins, nor result in us having to debug end-user code.

**Closed by brian-brazil** 2018-02-25 10:59 UTC

**Comment by roidelapluie** [comment] 2018-02-25 11:22
Is there a plan to move existing integrations to standalone daemons?

**Comment by onorua** [comment] 2018-02-25 11:23
Not sure you can tell that plugin request is duplication of jsonnet templating support inside core, except several comments in that ticket. 

About plugins (from Hashicorp), all you need is gRPC support, you can register plugins and deregister, as it happens with Vault, or load them dynamically based on configuration as it happens with terraform.

**Comment by brian-brazil** [comment] 2018-02-25 11:38
gRPC support is not as common as HTTP+JSON which we already have.

**Comment by onorua** [comment] 2018-02-25 11:39
Difference between Web hook and gRPC based plugin is bi-directional communication (asynchronous callbacks). Many of users have bosses, which wants to use Prometheus and CNCF best practices, but don't want to create Web hook gateway themselves, as you need to have HA for that. 
With plugin system done right, anyone can have HA notification agent (the sole purpose of alert-manager) without building 3rd party web hook gateway.
Let say, plugin can have health check built in, and if health check is failing, another alert-manager should do the notification. 
There are a lot of other use cases for plugin system. And yes, I believe existing integrations should be moved out to plugins as well.

**Comment by brian-brazil** [comment] 2018-02-25 11:44
> but don't want to create Web hook gateway themselves, as you need to have HA for that.

That's not how any of this works. The webhook receiver could be local, and if the notification fails on one Alertmanagers the others will send it through theirs.

Plugins do not in any way address solve your claimed problems, as you'd have the exact same architecture and work to do with a webhook receiver.

**Comment by onorua** [comment] 2018-02-25 12:03
OK, lets imagine HTTP+JSON will solve all the problems you may have ever face. Lets put yourself in the ordinary user's shoes. Where should I look for if I want integration with HTTP+JSON Web hook for alert manager? 

I know where to look for if I want integration for terraform:
https://github.com/terraform-providers

But with current approach, I want to have Telegram integration, and look for telegram inside alertmanager repo, and find out that telegram, and a lot of integrations rejected because it can be easily done with perfectly designed web hook. But there is not a word how to actually do this in that tickets I mentioned. So you start searching the web, and you found out that there are dozen of integrations using web hook for the telegram, which one should I pick? 

My main concern, there is no ecosystem for users to make educated decision which tool is good and which one is not. This could be done with plugin system, I really don't care whether it is HTTP+JSON, gRPC or any other protocol of communication, what I care - is that I can find a solution to my integration problem in timely manner without creating labs for dozen of alert solutions.

**Comment by brian-brazil** [comment] 2018-02-25 12:12
The technology choice doesn't affect how you find integrations nor how they are curated. We list them at https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver for example.
