### ISSUE TITLE
Enforce that alert contains labels

### ISSUE THREAD

**Issue by jomach** [prometheus/alertmanager#2187] opened 2020-02-18 10:58 UTC
**What did you do?**
I would like to know if it possible to configure alertmanager to to acknowledge the incoming alert if it has not a give labels. 

Ideia: It should be possible to return 403 if the post request to the alert manager does not contain a label that we need for routing it over the routes. 
Example of label that we want to enforce: 
    jira-dest-project: SOMEPROJECTID 

If a system sends an alert to the alert manager and we set in the config that a given labels must exist the return code should be 403 if the label is not present

**Comment by roidelapluie** [comment] 2020-02-18 13:15
Thanks for your report.

Here is my opinion:

Alertmanager should not fail on something that as a missing label. Our mission is to send alerts. If an alert is sent to the alertmanager, we should simply accept it and try to transmit it in all cases.

1. You can, if you wish, redirect the alerts that to not contain anything to a dedicated receiver, to take the action of fixing the alert.
1. It is important to note that it is not obvious to detect when prometheus can not send an alert to alertmanager. So such cases would be difficult to diagnose.
1. You can define default values for labels inside prometheus if you wish so, and that will be applied to every alerts (one example is the external labels).

**Comment by jomach** [comment] 2020-02-18 14:34
Hi @roidelapluie  thanks for you comment. Let's assume that we have multiple systems publishing alerts to alertmanager and not only prometheus. 

Somehow I need to achieve point 2. from your comments as then each source system can have a log message that the alert could not be send. 
The default values is a good tip but it is not going to enforce that one alert has a specific label. 

How about having a config like this: 
`
enforced_labels: 'jira-dest-project'
`
This way if the alertmanager has the config enforced_labels set all alerts need to have at least one of the label key defined on the config.

**Comment by brian-brazil** [comment] 2020-02-18 14:37
Authorisation features are out of scope for the alertmanager. If you need them a reverse proxy would be one approach.

**Comment by roidelapluie** [comment] 2020-02-18 14:38
> Hi @roidelapluie thanks for you comment. Let's assume that we have multiple systems publishing alerts to alertmanager and not only prometheus.

https://prometheus.io/docs/alerting/clients/

We strongly discourage that.

**Comment by simonpasquier** [comment] 2020-02-18 15:23
What @brian-brazil says, a reverse proxy in front of Alertmanager should do the trick. What you're asking for doesn't make sense for the vast majority of Alertmanager users.

**Comment by jomach** [comment] 2020-02-18 15:47
@brian-brazil it has nothing to do with Authorisation or Authentication. Is more about ensure that the payload has some schema that we can configure.  But thanks for the feedback.

**Closed** 2020-02-18 17:38 UTC

**Comment by eightnoteight** [comment] 2022-08-13 11:34
> Hi @roidelapluie thanks for you comment. Let's assume that we have multiple systems publishing alerts to alertmanager and not only prometheus.
> 
> Somehow I need to achieve point 2. from your comments as then each source system can have a log message that the alert could not be send.
> The default values is a good tip but it is not going to enforce that one alert has a specific label.

Hi @roidelapluie , we are facing a similar problem. we basically have a dedicated listener already for alerts that don't have a specific label that we use for routing. here the problem is that we want to use different dedicated listeners depending on the caller. 

for example, we have one system(not prometheus) that triggers alerts for jobs that are about to expire and another system(not prometheus) that triggers alerts for experiments that are about to expire. each of these systems are maintained by different teams. now if a job or experiment doesn't have proper labels then the team maintaining these systems will get an alert to make sure that all jobs and experiments have labels. so in this case we need to be able to use a different listener based on some missing labels.

one other solution I'm thinking is if alertmanager exposes `username` from basic authentication as a label automatically, something like `__alertmanager_basic_auth_username__` and the username, in the config depending on this label different default listener can be used. WDYT?
