### ISSUE TITLE
Reload not working

### ISSUE THREAD

**Issue by jangrewe** [prometheus/alertmanager#413] opened 2016-06-28 15:51 UTC
i'm running
```curl -X POST http://127.0.0.1:9093/-/reload```
and get the output 
```Reloading configuration file...```
and the log also shows 
```time="2016-06-28T15:47:13Z" level=info msg="Loading configuration file" file="/etc/alertmanager/config.yml" source="main.go:150"```
but the config shown in `/#/status` is still the old one.

This is on alertmanager 0.2.1 / revision 3f1c996

**Comment by fabxc** [comment] 2016-08-08 08:26
The logs are not showing any errors when parsing/loading the configuration?
Does the issue still exist in 0.3.0?

**Comment by fabxc** [comment] 2016-08-23 12:24
@jangrewe can you please provide some more information on this one. Reloading a valid config file works for me. An invalid file will show "Loading configuration file" in the logs, but is directly followed by the respective error.

If we don't have any further steps to reproduce, I'll assume this issue is resolved by now.

**Comment by jangrewe** [comment] 2016-08-24 13:24
I gotta test with alertmanager again, but i'm also having this issue with Prometheus (1.0.1).
There's nothing else in the log except:
```
time="2016-08-24T13:22:14Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:206"
```

if it's relevant: that YAML is mounted into the Docker container

**Comment by raypettersen** [comment] 2016-10-10 10:39
Shouldn't this be closed? Reloading is working fine (0.4.2).

**Comment by fabxc** [comment] 2016-10-10 11:35
I think it has always been working for most people. As there were no further reports from other users, I'm closing here.
This seems either like a deployment issue with Docker or the reloaded config file being invalid, which should be logged nowadays.

**Closed by fabxc** 2016-10-10 11:35 UTC
Labels: area/usability, component/config, kind/bug, priority/P1

**Comment by trendsoa** [comment] 2016-12-21 06:01
just tried version 0.5.1, it can not wok

curl -X POST http://localhost:9093/-/reload only show "Loading configuration file" and no error message, only after restart alertmanager, status page show latest config.

docker run --restart=unless-stopped -p 9093:9093 -v /opt/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml -v /opt/alertmanager/data:/alertmanager --detach=true --name=alertmanager prom/alertmanager:v0.5.1 -config.file=/etc/alertmanager/alertmanager.yml -storage.path=/alertmanager

**Comment by brancz** [comment] 2016-12-21 10:36
IIRC when mounting single files into docker they either don't get remounted on changes. Can you try mounting the configuration into the container by mounting an entire directory instead of just a single file. I recall a similar issue on prometheus/prometheus recently but can't seem to find it. I think @juliusv had previously answered that.

**Comment by juliusv** [comment] 2016-12-21 17:53
Yeah, that was on the Prometheus mailing list. You need to mount in an
entire directory, otherwise the Docker container won't pick up the changes
to the file on the host system (probably because it creates a new inode for
the changed file or something).

**Comment by pracplayopen** [comment] 2021-02-09 05:38
will say that i also had this issue after never having experienced it before.

was unable to even change the name of an existing alert and get it to take affect via restartinig alert manager.

been a while since i've done this myself so perhaps forgot something, but was unable to get even a name change to existing alert to take affect via restarting alert manager.    neither sighup, posting to reload endpoint, nor a kill/start of alert manager caused it to read new config.

eg

```
$ promtool check config bin/.prometheus.yml 
Checking bin/.prometheus.yml
  SUCCESS: 1 rule files found

Checking /home/tc/bin/.prom.alerts.yml
  SUCCESS: 15 rules found

$ restart-alertmanager.sh 
level=info ts=2021-02-09T05:15:18.787381012Z caller=main.go:311 msg="Loading configuration file" file=/home/tc/bin/.alertmanager.ppalerts.yml
$
```

After doing this, it would only show 14 rules in the UI (not the 15 above).   No errors or anything, just not there.
Tried reverting file and simply changing a name, same thing.

Only restarting prometheus itself (-SIGHUP) allowed the changes to show up.   Spent a goood 30min on this when expected to spend about 30 seconds, so leaving evidence here in case happens to others.
