### ISSUE TITLE
alertmanager don't update labels in alert

### ISSUE THREAD

**Issue by szediktam** [prometheus/alertmanager#1975] opened 2019-07-27 03:40 UTC
I install a prometheus(v2.2.1) and alertmanager(v0.18.0) in a k8s cluster.
I create a alertingrule in prometheus, as following:
```
groups:
- name: general
  rules:
  - alert: node-alert
    expr: node_load15{instance="172.18.21.158:.*"} > 1
    for: 60s
    labels:
      alert_severity: high
```
and I notify it to my app via alertmanager's webhook.

But when update the alertingrule to:
```
groups:
- name: general
  rules:
  - alert: node-alert
    expr: node_load15{instance="172.18.21.158:.*"} > 1
    for: 60s
    labels:
      node_name: test
      node_ip: 172.18.21.158
      severity: high
```
The alert received from webhook has no the added labels in alerts.

I think the alert received from webhook should same to the alertingrule in prometheus.
May be it is a bug of alertmanager.

**Comment by szediktam** [comment] 2019-07-27 03:50
@fabxc @brancz or someone else have a look at this question. Thanks.

**Comment by simonpasquier** [comment] 2019-07-29 08:02
It has nothing to do with AlertManager IMO and most probably a duplicate of https://github.com/prometheus/prometheus/issues/5193. You need to upgrade to the latest version of Prometheus.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Closed by simonpasquier** 2019-07-29 08:02 UTC
