### ISSUE TITLE
date/time picker for create silences page

### ISSUE THREAD

**Issue by gouthamve** [prometheus/alertmanager#1093] opened 2017-11-11 07:07 UTC
`/silences/new` and editing of silences currently has a string input for time fields. A timepicker like the one in the Prometheus graph UI is better.

```
goutham@iithserver1:~/alertmanager$ ./alertmanager --version           
alertmanager, version 0.10.0 (branch: HEAD, revision: 133c888ef3644b47a52acbaeffb09f4cc637df1b)
  build user:       root@01302b7cd08a
  build date:       20171109-15:34:53
  go version:       go1.9.2
```

**Comment by stuartnelson3** [comment] 2017-11-11 13:47
It's probably an unpopular opinion, but I find the current datetime selection for silences to be fairly simple and unambiguous, especially thanks to the duration selection. This is something we can definitely evaluate if it's desired, but I'm not sure we can unequivocally say that the prometheus datetime picker is better. But, as mentioned, just my opinion.

**Comment by w0rm** [comment] 2017-12-10 11:47
I'm not sure about this too. My hope is that the default `startsAt=now` and the duration field is good enough.  Datetime pickers are usually pretty complicated: 

1. the ui has a lot of elements and it is hard to make it accessible
2. it may not be the best way to input UTC timestamps
3. this brings in some localisation challenges (e.g. what is the first day of week, AM/PM or military)

**Comment by solongtony** [comment] 2020-08-14 13:46
Please don't dismiss a feature enhancement because you personally prefer a different way of doing things.  For different people in different circumstances different options will be better.  Last night I was dealing with a page at 1 in the morning.  I had worked with another team to determine the cause and impact, and we had decided they would work on fixing it after the weekend.  I tried to enter something like "3d 12hrs" as a duration, but I got an error that my input was invalid. I then had to use a calculator to figure out the exact timestamp of when I wanted the silence to end in three and a half days.  It would have been much easier with a date/time picker.

**Comment by solongtony** [comment] 2020-08-14 13:46
Also, this may be a duplicate of https://github.com/prometheus/alertmanager/issues/2226

**Comment by w0rm** [comment] 2020-08-14 13:56
@solongtony https://github.com/prometheus/alertmanager/pull/2262 has been merged. I think we can close this issue.

**Closed by w0rm** 2020-08-14 13:56 UTC
Labels: area/usability, component/ui, kind/enhancement, priority/Pmaybe
