### ISSUE TITLE
Additional fields for different notification HTTP requests

### ISSUE THREAD

**Issue by jsuchenia** [prometheus/alertmanager#1345] opened 2018-04-28 11:18 UTC
** Functional request - additional fields for outgoing notification calls **
When sending messages to *Slack* or *Pagerduty* we can add additional elements in JSON data to "enhance" it. Like attachments for Slack or Links for PagerDuty

It could be very useful if we can add "custom" fields from a template to each outgoing request. Of course usability of that require knowledge of service API but it's possible. Now number of supported fields is limited in notification implementation and can't be changed without alertmanager recompilation

** Proposal **
For each HTTP based system we can have an object called `context` or `params` generated from a template and it can be added to the body of each request (or only to trigger, or only to cancel request)

It should allow better integration with almost all supported services

**Comment by Grummfy** [comment] 2018-05-17 09:47
Totally fan of it, I would love to have it.

**Comment by brian-brazil** [comment] 2018-05-17 10:15
Dupe of #701 as you're basically asking for arbitrary json.

**Closed by brian-brazil** 2018-05-17 10:15 UTC
Labels: area/usability, component/notify, kind/enhancement
