### ISSUE TITLE
Possible bug when expiring a silence in v0.5.1

### ISSUE THREAD

**Issue by mattbostock** [prometheus/alertmanager#578] opened 2016-12-12 23:10 UTC
I tried out version 0.5.x today. It looks like I've hit a bug:

1. Create a test alert.

2. Click the 'Silence' button for the alert, add a comment and email address. Leave the other fields as-is.

3. Expire the silence.

4. The silence will show under 'Elapsed', but the alert still has the yellow 'silenced' label on the Alerts page. I would not have expected the alert to show as silenced.

**Comment by brancz** [comment] 2016-12-12 23:22
Is it only displayed to be a silenced and you are still getting the notification, or is it actually still silencing?

**Comment by brancz** [comment] 2016-12-13 00:04
I can sort of reproduce this, for some reason I'm having quite a long delay ~3 minutes before a silence starts having an effect and same for when a silence expires .. it takes ~3 minutes before the previously silenced alerts are not displayed as silenced anymore. /cc @fabxc

**Comment by brancz** [comment] 2016-12-13 01:39
It seems a bit too consistent to me, is this intended behavior @fabxc ?

**Comment by fabxc** [comment] 2016-12-13 03:56
We flag alerts as silenced or inhibited whenever we reevaluate the alert group for sending. 
So if a 5 minute `group_interval` is running, it may still be showed as silenced for that amount at time but at no point does it influence the defined behavior.

If it is longer, i.e. a silence actually has prolonged effect and causes a notification to not be sent, it's indeed a bug.
Otherwise that's the behavior that has always been there and shouldn't be a 5.x thing.

Re-evaluating all that stat on every UI page load would definitely not scale. Ideally, we'd have some sort of in-memory cache on these that's properly invalidated on any change.

**Comment by brian-brazil** [comment] 2018-03-29 10:38
Dupe of #190

**Closed by brian-brazil** 2018-03-29 10:38 UTC
Labels: area/usability, component/silences, kind/bug, priority/Pmaybe
