### ISSUE TITLE
JFYI: Outdated Dockerfile at docker hub

### ISSUE THREAD

**Issue by lexfrei** [prometheus/alertmanager#1303] opened 2018-03-28 16:16 UTC
Hello!
You got outdated dockerfile at docker hub.
https://hub.docker.com/r/prom/alertmanager/~/dockerfile/
JFYI, feel free to close this issue.

**Comment by simonpasquier** [comment] 2020-10-13 12:24
It is a dupe of https://github.com/docker/hub-feedback/issues/1847. Unfortunately we got no update from the project :disappointed:

**Closed by simonpasquier** 2020-10-13 12:24 UTC
