### ISSUE TITLE
how to make the event of no datapoint found  to trigger alarm

### ISSUE THREAD

**Issue by zouyee** [prometheus/alertmanager#494] opened 2016-09-07 14:43 UTC
![qw](https://cloud.githubusercontent.com/assets/5785605/18316264/872e3ce6-754c-11e6-8a3a-56b6b8c327d9.png)

**Comment by juliusv** [comment] 2016-09-08 02:40
This seems to be a dupe of https://github.com/prometheus/prometheus/issues/1956. Closing.

**Closed by juliusv** 2016-09-08 02:40 UTC
