### ISSUE TITLE
Missing option to filter alerts by receiver

### ISSUE THREAD

**Issue by grobie** [prometheus/alertmanager#863] opened 2017-06-14 15:42 UTC
With the new UI introduced in v0.7 I can't find an option to show all alerts assigned to me/my receiver. As team with diverse responsibilities, very different label combinations end up in my receiver.

Is there any workaround? I tried the label `receiver="my-team"` but that didn't work.

**Comment by mxinden** [comment] 2017-06-15 11:04
Duplicate of #800. Closing here. Please reopen if I am mistaken. As far as I am aware there is no workaround.

**Closed by mxinden** 2017-06-15 11:04 UTC
Labels: component/ui, kind/regression

**Comment by grobie** [comment] 2017-06-15 12:28
Oops, thanks @mxinden. I missed that, but can I ask to prioritize it? It's quite hard to see all alerts for my team now.

**Comment by mxinden** [comment] 2017-06-15 13:44
@grobie No worries. It is part of the 0.8 milestone, so we would add it in the upcoming release.
